### ISSUE TITLE
[DOCS] Add process/guide - "How to archive a repo"

### ISSUE THREAD

**Issue by Pradumnasaraf** [Pradumnasaraf/open-source-with-pradumna#100]
### Description

Hey! Contributor,

This issue is for adding the guide/process for **How to archive a repo**. The step needs to be well defined and include the Screenshot/Screen recording for better explanation. To get an overview of how the docs should look, check the available docs [`here`](https://github.com/Pradumnasaraf/open-source-with-pradumna/blob/main/pages/How-to/guide)

- Path to the dedicate Markdown for this issue - [`open-source-with-pradumna/pages/How-to/guide/archive-repo.md`](https://github.com/Pradumnasaraf/open-source-with-pradumna/blob/main/pages/How-to/guide/archive-repo.md)

---

If you have any suggestions feel free to Open an [Issue](https://github.com/Pradumnasaraf/open-source-with-pradumna/issues)

**Also if you need any kind of help, feel free to ping!**

**Comment by Lokeshkhati** [comment]
Hey, @Pradumnasaraf  can you please assign this issue to me, I would love to contribute.

Thank you

**Comment by Pradumnasaraf** [comment]
Hey, @Lokeshkhati, thank you for your interest. Go ahead will the issue.

**Comment by trenz999** [comment]
@Pradumnasaraf Please the doc on how to achieve repo is not clear, can it be updated
