### ISSUE TITLE
[DOCS] Add process/guide - "How to make a repo private/public"

### ISSUE THREAD

**Issue by Pradumnasaraf** [Pradumnasaraf/open-source-with-pradumna#101]
### Description

Hey! Contributor,

This issue is for adding the guide/process for **How to make a repo private/public**. The step needs to be well defined and include the Screenshot/Screen recording for better explanation. To get an overview of how the docs should look, check the available docs [`here`](https://github.com/Pradumnasaraf/open-source-with-pradumna/blob/main/pages/How-to/guide)

- Path to the dedicate Markdown for this issue - [`open-source-with-pradumna/pages/How-to/guide/repo-private-public.md`](https://github.com/Pradumnasaraf/open-source-with-pradumna/blob/main/pages/How-to/guide/repo-private-public.md)

---

If you have any suggestions feel free to Open an [Issue](https://github.com/Pradumnasaraf/open-source-with-pradumna/issues)

**Also if you need any kind of help, feel free to ping!**

**Comment by nitin-nagaraj-au26** [comment]
@Pradumnasaraf I'm interested in working on this.

**Comment by hasnainmakada-99** [comment]
Hey @Pradumnasaraf I would like to work on this issue, But it seems that the link which you provided is broken

**Comment by itzwow** [comment]
Hello @Pradumnasaraf  I would like to work on this issue.

**Comment by Pradumnasaraf** [comment]
Hey @nitin-nagaraj-au26, thank you for your interest. Go ahead will the issue.

**Comment by Pradumnasaraf** [comment]
Hey, @hasnainmakada-99 @itzwow, look for other issues, as someone other has already shown the interest.

**Comment by hasnainmakada-99** [comment]
Ok @Pradumnasaraf no problem

**Comment by itzwow** [comment]
Alright @Pradumnasaraf

**Comment by kelvinparmar** [comment]
@Pradumnasaraf  Anyone is working on this issue?

**Comment by Pradumnasaraf** [comment]
Hey, @nitin-nagaraj-au26  hope you working on this issue.

If yes, I will recommend opening PR after the 1st of October so that it can count towards your Hactoberfest contribution smile

**Comment by nitin-nagaraj-au26** [comment]
Hi @Pradumnasaraf, yes I'm working on this and will open the PR accordingly. Thanks.

**Comment by yash251** [comment]
Are you still working on it ?
If not, I'd like to take up on this issue.

**Comment by nitin-nagaraj-au26** [comment]
@Pradumnasaraf I have raised a PR for this, kindly look into it and let me know if any changes need to be added.
