### ISSUE TITLE
[PR] <Suggesstion to add some topics>

### ISSUE THREAD

**Issue by ShubhamJagtap2000** [Pradumnasaraf/open-source-with-pradumna#105]
### Description

Just checked your recent commits to the repo. The job that you are doing really helped me the last few days to make myself more sound about how and what actually happens while fork, raising a PR, etc. As I see you have covered many basic, core topics. What I felt was difficult while learning is the concept of **<ins>git stash, squashing the repo, and concepts like upstream, git rebase and git reset</ins>**. It will be ***`a cherry on the cake`*** if you add this topic in the repo and blogs as soon as possible. As I have also seen many of my friends struggle with these concepts. 

Thank you.

**Comment by Pradumnasaraf** [comment]
Thank you for the appreciation and opening issue. Can you add those suggestions to the Discussion here? https://github.com/Pradumnasaraf/open-source-with-pradumna/discussions/31

**Comment by ShubhamJagtap2000** [comment]
Sure
