### ISSUE TITLE
[BUG] Add alt attribute to images

### ISSUE THREAD

**Issue by developer-diganta** [Pradumnasaraf/open-source-with-pradumna#107]
### Description

I think adding alt attribute would make the web page more accessible. If this seems something to work upon, can I do it?

**Comment by Pradumnasaraf** [comment]
Thank you for raising an issue. Yes, go ahead. You can work on this.

**Comment by RohitRajvaidya5** [comment]
is this issue resolved? can I work on it?

**Comment by Pradumnasaraf** [comment]
Hey, @developer-diganta in which section of the repo you are adding `alt text? can you do it only for the [root README](https://github.com/Pradumnasaraf/open-source-with-pradumna/blob/main/README.md), so that I can open issue for the part of the repo and give more space for other contributors.

**Comment by developer-diganta** [comment]
@Pradumnasaraf I saw that the root README has the alt texts. I guess I can one section (Bootcamp) ones, then the other ones can be picked up by other people. What do you say?

**Comment by Pradumnasaraf** [comment]
> @Pradumnasaraf I saw that the root README has the alt texts. I guess I can one section (Bootcamp) ones, then the other ones can be picked up by other people. What do you say?

Sounds great, will be waiting for your PR. 
Thank you!

**Comment by developer-diganta** [comment]
@Pradumnasaraf Done!
