### ISSUE TITLE
[DOCS] Add process - "how to create a PR Template" 

### ISSUE THREAD

**Issue by Pradumnasaraf** [Pradumnasaraf/open-source-with-pradumna#11]
### Changes/Action required
 
 - Add a complete process of **how to create a PR**, steps will contain a text, screenshot, Video (it can be screen recording to show the steps) and GIF (if needed)
 
- Path of the file in which **steps** need to be added - [`open-source-with-pradumna/pages/How-to/guide/adding-pr-template.md`](https://github.com/Pradumnasaraf/open-source-with-pradumna/blob/main/pages/How-to/guide/adding-pr-template.md)

---

If you have any suggestion feel free to Open an [Issue](https://github.com/Pradumnasaraf/open-source-with-pradumna/issues)
 

#### This addition of the documentation will get added and hyperlinked in [`How-to/README.md`](https://github.com/Pradumnasaraf/open-source-with-pradumna/tree/main/pages/How-to) and also get hosted on the website https://Opensource.pradumnasaraf.co

![Screenshot from 2022-05-15 14-11-21](https://user-images.githubusercontent.com/51878265/168464628-905b0a25-627b-4560-b8e4-bd09940d8c7b.png)

**Comment by KendallDoesCoding** [comment]
I would like to work on this

**Comment by SuperAayush** [comment]
Hey, @Pradumnasaraf I would love to work on this 😄.

**Comment by Pradumnasaraf** [comment]
> Hey, @Pradumnasaraf I would love to work on this smile.

Hey! Aayush, thank you for your interest. Yes you can work on this :rocket:

**Comment by Pradumnasaraf** [comment]
Hey, @SuperAayush thank you for your interest.

 I just realized, by mistake, that I forgot to add the "**template"** word in the heading. This issue is for creating a PR template. The issue for the PR guide is already assigned (#16)
 
 Sorry for the inconvenience, you can work on this issue or some other one

**Comment by Pradumnasaraf** [comment]
> Can I take this? @Pradumnasaraf

Sure Asmit, Thank you for your interest.

Hey!, @SuperAayush, just for the confirmation you are not working on this, right?

**Comment by SuperAayush** [comment]
Yes, I will be going for PR today itself 😄

**Comment by Pradumnasaraf** [comment]
Hey, @SuperAayush just a slight nudge, waiting for your PR :)

**Comment by SuperAayush** [comment]
@Pradumnasaraf PR is ready but I am stuck with the Video, I read about the video part later when I was going to commit can you lend me some time.
I am thinking to make a youtube video and then attach that will that work?
Or do you want only the screen recording?
I am really sorry to keep you waiting 🥲.

**Comment by Pradumnasaraf** [comment]
> PR is ready but I am stuck with the Video, I read about the video part later when I was going to commit can you lend me some time.

Haha, why you are saying me sorry and asking me to lend you time:), you can take your time. I was just checking up if you haven't caught up in any kind of issue.

Yes yes, Screen recording is totally and that's what is required, feel free to add it. If you have any doubts feel free to reach out.
Take your time and thank you for your time and effort !!.

**Comment by Pradumnasaraf** [comment]
Hey! @SuperAayush, want to confirm, that are you still working on this issue :) ?

**Comment by SuperAayush** [comment]
@Pradumnasaraf I have created a Video without Audio 🤔, since you only wanted the screen recording
