### ISSUE TITLE
[DOCS] Improvement for more ease in project

### ISSUE THREAD

**Issue by ShubhamJagtap2000** [Pradumnasaraf/open-source-with-pradumna#110]
### Description

Hello, @Pradumnasaraf I just found some documentation as well as bug improvement in the [cloning repo](https://github.com/Pradumnasaraf/open-source-with-pradumna/blob/main/pages/How-to/guide/cloning-repo.md) file. I think a direction about copy-paste in Git Bash needs to be added with an image. It will be good for a beginner not to be stuck for a moment(as I did not knew when I used ctrl + v). Can I add that?

**Comment by Pradumnasaraf** [comment]
Thank you for raising the issue. Yes go ahead

**Comment by ShubhamJagtap2000** [comment]
Just done with it, you can review [here](https://github.com/Pradumnasaraf/open-source-with-pradumna/pull/113).
