### ISSUE TITLE
[BUG] Add alt attribute to the images in `How to` page

### ISSUE THREAD

**Issue by Pradumnasaraf** [Pradumnasaraf/open-source-with-pradumna#115]
### Description

Link to the page  - https://github.com/Pradumnasaraf/open-source-with-pradumna/blob/main/pages/How-to/README.md

### Screenshots

_Not required_

**Comment by lazyturd** [comment]
Hey, can I be assigned to this?

**Comment by Pradumnasaraf** [comment]
Thank you for your interest, go ahead

**Comment by MahendraBishnoi29** [comment]
@Pradumnasaraf couldn't find any img tags there?

**Comment by Pradumnasaraf** [comment]
> @Pradumnasaraf couldn't find any img tags there?

Thnak you for pointing it out. Yes it's not there

**Comment by hasnainmakada-99** [comment]
Is this issue resolved @Pradumnasaraf , If not can I work on it ?

**Comment by Pradumnasaraf** [comment]
Hey @lazyturd, I will recommend opening PR after the 1st of October so that it can count towards your Hactoberfest contribution smile.

**Comment by lazyturd** [comment]
> 

Noted sir. Thanks

**Comment by ardasevinc** [comment]
@lazyturd Hello, are you still working on this?

**Comment by lazyturd** [comment]
> @lazyturd Hello, are you still working on this?

Yes I am. Sending a pull request today

**Comment by Pradumnasaraf** [comment]
Hey, @lazyturd are still working on this PR?

**Comment by pritipsingh** [comment]
Hey I would like to work on it
