### ISSUE TITLE
[BUG] Add alt attribute to the images in the root README

### ISSUE THREAD

**Issue by Pradumnasaraf** [Pradumnasaraf/open-source-with-pradumna#116]
### Description

Link to the page - https://github.com/Pradumnasaraf/open-source-with-pradumna

### Screenshots

_Not required_

**Comment by MahendraBishnoi29** [comment]
@Pradumnasaraf there's only 1 image and the alt is already there 🤔

**Comment by Athithya-t** [comment]
Hi @Pradumnasaraf 
Can I work on this issue?

**Comment by Pradumnasaraf** [comment]
> Hi @Pradumnasaraf Can I work on this issue?

Yes, go ahead. Thnak you for your intrest.
