### ISSUE TITLE
[BUG] Add alt attribute to the images in `Learning resources` page

### ISSUE THREAD

**Issue by Pradumnasaraf** [Pradumnasaraf/open-source-with-pradumna#117]
### Description

Link to the page - https://github.com/Pradumnasaraf/open-source-with-pradumna/blob/main/pages/Resources.md

### Screenshots

_Not required_

**Comment by yung-coder** [comment]
I would like to do this...

**Comment by Pradumnasaraf** [comment]
> I would like to do this... @Pradumnasaraf

Go ahead, thank you. Assigning top you

I will recommend opening PR after the 1st of October so that it can count towards your Hactoberfest contribution :smile:

**Comment by yung-coder** [comment]
Okay assign it i will open it after 1 oct . Thanks 🙏

**Comment by yung-coder** [comment]
hey @Pradumnasaraf  i looked at it and the alt tags are already their ...?

**Comment by Vishrut19** [comment]
Hey @Pradumnasaraf I can work on this issue

**Comment by Pradumnasaraf** [comment]
> hey @Pradumnasaraf i looked at it and the alt tags are already their ...?

Sounds cool, then let's close this
