### ISSUE TITLE
[BUG] Add alt attribute to the images `regular content` page

### ISSUE THREAD

**Issue by Pradumnasaraf** [Pradumnasaraf/open-source-with-pradumna#118]
### Description

Link to the page - https://github.com/Pradumnasaraf/open-source-with-pradumna/blob/main/pages/Regular.md

### Screenshots

N/A

**Comment by xcelr8** [comment]
Hi, can I work on this issue?

**Comment by Ski1ledHawkeye** [comment]
Hey i'm interested in this issue. Can you assign me this one ?
