### ISSUE TITLE
[DOCS] Add process/guide - "How to create an Issue"

### ISSUE THREAD

**Issue by Pradumnasaraf** [Pradumnasaraf/open-source-with-pradumna#12]
### Changes/Action required
 
 - Add a complete process of "How to create an Issue", steps will contain a text, screenshot, Video (it can be a screen recording to show the steps), and GIF (if needed)
 
- Path of the file in which **steps** need to be added - [`open-source-with-pradumna/pages/How-to/guide/rasing-issue.md`](https://github.com/Pradumnasaraf/open-source-with-pradumna/blob/main/pages/How-to/guide/rasing-issue.md)

---

If you have any suggestions feel free to Open an [Issue](https://github.com/Pradumnasaraf/open-source-with-pradumna/issues)
 

#### This addition of the documentation will get added and hyperlinked in [`How-to/README.md`](https://github.com/Pradumnasaraf/open-source-with-pradumna/tree/main/pages/How-to) and also get hosted on the website https://Opensource.pradumnasaraf.co

![Screenshot from 2022-05-15 14-11-21](https://user-images.githubusercontent.com/51878265/168464628-905b0a25-627b-4560-b8e4-bd09940d8c7b.png)

**Comment by akebu6** [comment]
Hey Pradumna, I would like to work on this but does this involve adding steps for all the different types of issues you can create in this repo?

**Comment by Pradumnasaraf** [comment]
> Hey Pradumna, I would like to work on this but does this involve adding steps for all the different types of issues you can create in this repo?

Hey Akebu, thank you for the interest.
For now, we can only plain one (the non-template one)

**Comment by akebu6** [comment]
Okay, then I can do it. Is there a timeline when it should be submitted? Asking because for the next few days I have a ton of classes to catch up on

**Comment by Pradumnasaraf** [comment]
> Okay, then I can do it. Is there a timeline when it should be submitted? Asking because for the next few days I have a ton of classes to catch up on

You can take your time, **Akebu** :)

**Comment by Pradumnasaraf** [comment]
Hey, @akebu6  just a slight nudge, waiting for your PR :)

**Comment by akebu6** [comment]
I was actually working on it, you should have it in a few hours.

**Comment by Pradumnasaraf** [comment]
> I was actually working on it, you should have it in a few hours.

Thank you Akeku, I was just checking either if you haven't been caught in some kind of problem or not. Take your time.

**Comment by akebu6** [comment]
Should I also add a video or screenshots will be sufficient?

**Comment by Pradumnasaraf** [comment]
> I was held up with school work, otherwise I'd have done it that same day.
> 
> Should I also add a video or screenshots will be sufficient? 

Oh sorry for the ping, didn't know that 😅.

You can leave screenshot, we will add later on.
Again sorry and thank you for your time.

**Comment by akebu6** [comment]
Oh it's all right lol, today is my day off school stuff. All right, then let me create the PR in that case since I don't have to add the screenshots

**Comment by Pradumnasaraf** [comment]
> Oh it's all right lol, today is my day off school stuff. All right, then let me create the PR in that case since I don't have to add the screenshots

Sorry, I mean you can leave the video part, it is possible for you to add 1 or 2 screenshots?

**Comment by akebu6** [comment]
I already have ones that I edited beforehand. Can I just add those?

**Comment by Pradumnasaraf** [comment]
> I already have ones that I edited beforehand. Can I just add those?

Yes yes, for sure you can add anything either screenshot to screen recording. Thank you!

Sorry for the confusion. My laptop screen is half-dead, so can't able to read the whole message from you.

**Comment by akebu6** [comment]
Created the PR, I had some issues with the images but got everything sorted out
