### ISSUE TITLE
[DOCS] Add eddie jaoude github course in learning resources

### ISSUE THREAD

**Issue by zabihhaqqani** [Pradumnasaraf/open-source-with-pradumna#122]
### Description

- The free course by eddie jaoude for improving a github profile can be added in the list of learning.
- [Eddie Jaoude Github Course](https://www.eddiejaoude.io/course-github-profile-landing?r_done=1)

**Comment by Pradumnasaraf** [comment]
Hey, thank you for opening the PR. Yes it's a great addition we can add that to the [learning resources page](https://github.com/Pradumnasaraf/open-source-with-pradumna/blob/main/pages/Resources.md)

**Comment by Pradumnasaraf** [comment]
Do you want to work on this PR @zabihhaqqani ?

**Comment by zabihhaqqani** [comment]
Yes but can we add Eddie's course in your learnings.

**Comment by Pradumnasaraf** [comment]
> Yes but can we add Eddie's course in your learnings.

Didn't get your points? As I mentioned above you can add that course to [Learning resources page](https://github.com/Pradumnasaraf/open-source-with-pradumna/blob/main/pages/Resources.md)

**Comment by zabihhaqqani** [comment]
Oh sorry my bad I am using the mobile version and it didn't show the above messages till I clicked on load more comments.

**Comment by Pradumnasaraf** [comment]
Awesome, I will recommend opening PR after the 1st of October so that it can count towards your Hactoberfest contribution

**Comment by zabihhaqqani** [comment]
Sure you can assign it to me 

I will open the PR after 1st Oct.

**Comment by zabihhaqqani** [comment]
Okay, did the changes but I have just copied the image URL from Eddie so will there be any copyright issues?

And the image is a bit large compared to others.

![4](https://user-images.githubusercontent.com/53895282/193246586-cfa32eff-fa26-4189-a22d-9f709eae62ac.PNG)

**Comment by Pradumnasaraf** [comment]
> Okay, did the changes but I have just copied the image URL from Eddie so will there be any copyright issues?
> 
> And the image is a bit large compared to others.
> 
> ![4](https://user-images.githubusercontent.com/53895282/193246586-cfa32eff-fa26-4189-a22d-9f709eae62ac.PNG)


It's good no worries.

**Comment by Vishrut19** [comment]
I would like to work on this issue @Pradumnasaraf

**Comment by Pradumnasaraf** [comment]
> I would like to work on this issue @Pradumnasaraf

The issue is already assigned, look for other issues

**Comment by zabihhaqqani** [comment]
I have sent the pull request for the above changes!
