### ISSUE TITLE
[DOCS] Center the images in the document

### ISSUE THREAD

**Issue by Pradumnasaraf** [Pradumnasaraf/open-source-with-pradumna#129]
### Description

Link to the docs - https://github.com/Pradumnasaraf/open-source-with-pradumna/blob/main/pages/How-to/guide/rasing-issue.md

**Comment by muditchoudhary** [comment]
Hey, @Pradumnasaraf I would like to work on this.

**Comment by Vishrut19** [comment]
Hey @Pradumnasaraf Can i work on this issue ?

**Comment by Pradumnasaraf** [comment]
> Hey, @Pradumnasaraf I would like to work on this.

Yes, go ahead @muditchoudhary
