### ISSUE TITLE
[DOCS] Add process/guide - "How to add sponsor button to a repo"

### ISSUE THREAD

**Issue by Pradumnasaraf** [Pradumnasaraf/open-source-with-pradumna#13]
### Changes/Action required
 
 - Add a complete process of **"Adding sponser to a repo"**, steps will contain a text, screenshot, Video (it can be a screen recording to show the steps), and GIF (if needed)
 
- Path of the file in which **steps** need to be added - [`open-source-with-pradumna/pages/How-to/guide/adding-sponsor.md`](https://github.com/Pradumnasaraf/open-source-with-pradumna/blob/main/pages/How-to/guide/adding-sponsor.md)

---

If you have any suggestions feel free to Open an [Issue](https://github.com/Pradumnasaraf/open-source-with-pradumna/issues)

#### This addition of the documentation will get added and hyperlinked in [`How-to/README.md`](https://github.com/Pradumnasaraf/open-source-with-pradumna/tree/main/pages/How-to) and also get hosted on the website https://Opensource.pradumnasaraf.co

![Screenshot from 2022-05-15 14-11-21](https://user-images.githubusercontent.com/51878265/168464628-905b0a25-627b-4560-b8e4-bd09940d8c7b.png)

**Comment by KendallDoesCoding** [comment]
@Pradumnasaraf Can I work on this please.

**Comment by Pradumnasaraf** [comment]
> @Pradumnasaraf Can I work on this please.

As I told you, let other beginners take the other issue, you already worked on lots of parts.

**Comment by VardaanAggarwal** [comment]
Hey @Pradumnasaraf I want to work on this issue !
Can I work on this ?

**Comment by Pradumnasaraf** [comment]
> Hey @Pradumnasaraf I want to work on this issue ! Can I work on this ?

Yes sure go ahead, thank you for the consideration.!!

**Comment by VardaanAggarwal** [comment]
Thanks !
I am starting to work on this .

**Comment by Pradumnasaraf** [comment]
Hey @VardaanAggarwal waiting for your PR :)

**Comment by VardaanAggarwal** [comment]
Hey @Pradumnasaraf , I am so sorry for the delay on my end due to some issues.
I will not be delayed more, I am 60% through the process of working on the issue !
Will create a PR very soon !
(Expected date of PR - 25th of June)

**Comment by Pradumnasaraf** [comment]
No worries, Thank you!!

**Comment by Pradumnasaraf** [comment]
Hey waiting for your. If you have any doubts feel free to ping me!

**Comment by Pradumnasaraf** [comment]
Hey, @VardaanAggarwal I am unassigning you from the issue.

**Comment by aryanraj2713** [comment]
Hey Is the issue still open?
Can I contribute?

**Comment by singh-saksham** [comment]
@aryanraj2713 I have already made a pull request for this issue

**Comment by singh-saksham** [comment]
@aryanraj2713 why dont you try #14

**Comment by aryanraj2713** [comment]
@singh-saksham  sure , I have checked #14
Pls assign it to me
