### ISSUE TITLE
[BUG] Add ALT attribute to doc

### ISSUE THREAD

**Issue by Pradumnasaraf** [Pradumnasaraf/open-source-with-pradumna#130]
### Description

Add proper ALT to the docs - https://github.com/Pradumnasaraf/open-source-with-pradumna/blob/main/pages/How-to/guide/creating-pr.md

### Screenshots

N/A

**Comment by YashPimple** [comment]
@Pradumnasaraf would like to work on this issue!

**Comment by Vishrut19** [comment]
Hey @Pradumnasaraf can I work on this issue ?

**Comment by hemantwasthere** [comment]
Hey @Pradumnasaraf, I would like to work on this issue. Please assign it to me

**Comment by Pradumnasaraf** [comment]
> @Pradumnasaraf would like to work on this issue!

Yes, go ahead @YashPimple . Okay, no worries I will open that closed PR.

**Comment by Pradumnasaraf** [comment]
Oops looks like you deleted the brach @YashPimple

**Comment by hemantwasthere** [comment]
@Pradumnasaraf, Can I do this if @YashPimple haven't done it
