### ISSUE TITLE
[DOCS] Center the images in doc

### ISSUE THREAD

**Issue by Pradumnasaraf** [Pradumnasaraf/open-source-with-pradumna#131]
### Description

Link to the doc - https://github.com/Pradumnasaraf/open-source-with-pradumna/blob/main/pages/How-to/guide/creating-pr.md

### Screenshots

N/A

**Comment by kakkarot0** [comment]
hey Pradumnasaraf i would like to work on this!

**Comment by hemantwasthere** [comment]
Hey @Pradumnasaraf, I would like to work on this issue. Please assign it to me

**Comment by Pradumnasaraf** [comment]
> Hey @Pradumnasaraf, I would like to work on this issue. Please assign it to me

I have already assigned you an Issue. Let other people contribute and join in. Thank you for understanding

**Comment by anuragh2002** [comment]
Hey @Pradumnasaraf I would like to work on this issue. Can you please assign it to me?

**Comment by Pradumnasaraf** [comment]
> Hey @Pradumnasaraf I would like to work on this issue. Can you please assign it to me?

Yes go ahead @anuragh2002

**Comment by shivamnarkar47** [comment]
Hey @Pradumnasaraf , I have sent you the pull request for it :+1:

**Comment by MuhammadNoorani** [comment]
Hey @Pradumnasaraf can I work on this issue, if this is yet pending ?

**Comment by ianujvarshney** [comment]
Hey @Pradumnasaraf  could you assisgn me please?
