### ISSUE TITLE
[DOCS] Improve the ALT text in docs

### ISSUE THREAD

**Issue by Pradumnasaraf** [Pradumnasaraf/open-source-with-pradumna#132]
### Description

Link to docs - https://github.com/Pradumnasaraf/open-source-with-pradumna/blob/main/pages/How-to/guide/adding-sponsor.md

### Screenshots

![Screenshot 2022-09-30 at 1 28 43 PM](https://user-images.githubusercontent.com/51878265/193221459-4b18a230-9abf-4399-9c60-293f7e9ba72e.png)

**Comment by PriyanshuAhlawat** [comment]
@Pradumnasaraf  pr created

**Comment by hemantwasthere** [comment]
Hey @Pradumnasaraf, I would like to work on this issue. Please assign it to me

**Comment by Pradumnasaraf** [comment]
> Hey @Pradumnasaraf, I would like to work on this issue. Please assign it to me

Yes go ahead @hemantwasthere

**Comment by hemantwasthere** [comment]
Hey @Pradumnasaraf , I have opened a PR, please check it out  

PR: #151

**Comment by hemantwasthere** [comment]
Hello @Pradumnasaraf, can you please check the PR and let me know if there is any vulnerability
