### ISSUE TITLE
[DOCS] Add some spacing between the points and center the images

### ISSUE THREAD

**Issue by Pradumnasaraf** [Pradumnasaraf/open-source-with-pradumna#133]
### Description

Link to the doc -  https://github.com/Pradumnasaraf/open-source-with-pradumna/blob/main/pages/How-to/guide/starting-discussion.md

### Screenshots

N/A

**Comment by iks1** [comment]
can you assign this to me ?

**Comment by Vishrut19** [comment]
Hey @Pradumnasaraf can I work on this issue ?

**Comment by PriyanshuAhlawat** [comment]
@Pradumnasaraf  created the pr

**Comment by hemantwasthere** [comment]
Hey @Pradumnasaraf, I would like to work on this issue. Please assign it to me

**Comment by Pradumnasaraf** [comment]
> can you assign this to me ?

Yes, go ahead @iks1

**Comment by imran1509** [comment]
hey, Can i work on this?

**Comment by Pradumnasaraf** [comment]
> hey, Can i work on this?

Hey, thank you for your interest, but the issue is already assigned to the other contributor, try finding some other issue. 

Thank you!

**Comment by tmsagarofficial** [comment]
@Pradumnasaraf Since i couldnt find any update regarding this issue can i give it a try? pls let me ASAP.

**Comment by Pradumnasaraf** [comment]
Hey, @iks1 are you still working on this Iusse? if no, I will assign it to someone else

**Comment by Pradumnasaraf** [comment]
I have unassigned the previous contributor, anyone would like to take up this issue?

**Comment by Vishrut19** [comment]
I would like to take the issue ! @Pradumnasaraf

**Comment by tmsagarofficial** [comment]
Yeah pls let me give it a try @Pradumnasaraf

**Comment by Pradumnasaraf** [comment]
Hey @Vishrut19, I just assigned you the Issue https://github.com/Pradumnasaraf/open-source-with-pradumna/issues/201

So, assigning this issue to @tmsagarofficial

**Comment by tmsagarofficial** [comment]
@Pradumnasaraf Hi again, Pls check and let me know if there should be any changes. 
I have done the necessary changes to address this issue to the best of my understanding and knowledge here in this pr #217

**Comment by tmsagarofficial** [comment]
@Pradumnasaraf pls check again.......sorry for the inconvenience

**Comment by tmsagarofficial** [comment]
@Pradumnasaraf Pls add the labels and Thanks for letting me contribute 🤝
