### ISSUE TITLE
[DOCS] Improve the ALT text in the docs

### ISSUE THREAD

**Issue by Pradumnasaraf** [Pradumnasaraf/open-source-with-pradumna#134]
### Description

Link to the docs - https://github.com/Pradumnasaraf/open-source-with-pradumna/blob/main/pages/How-to/guide/linking-issue-with-pr.md

### Screenshots

N/A

**Comment by kakkarot0** [comment]
can i work on this issue

**Comment by Pradumnasaraf** [comment]
> can i work on this issue

I have already assigned you an Issue. Let other people contribute and join in. Thank you for understanding

**Comment by PriyanshuAhlawat** [comment]
hey @Pradumnasaraf  I will like to work on this, can you assign this to me

**Comment by yashdev9274** [comment]
Hey @Pradumnasaraf if you don't mind, may I know what is this issue about ?

**Comment by thisisharsh7** [comment]
I would like to work on this issue. could you **please** assign it to me?

**Comment by Tamanna-S** [comment]
hello may i try @Pradumnasaraf

**Comment by Pradumnasaraf** [comment]
> hey @Pradumnasaraf I will like to work on this, can you assign this to me

Yes, you can work on it.

**Comment by Pradumnasaraf** [comment]
Hey, @thisisharsh7 @Tamanna-S , as the Priyanshu asked for it 1st so assigned it to them. Looks for other issue and soon I will open more.

**Comment by Pradumnasaraf** [comment]
> Hey @Pradumnasaraf if you don't mind, may I know what is this issue about ?

For adding ALT text to images

**Comment by Tamanna-S** [comment]
alright thank you!

**Comment by ianujvarshney** [comment]
Could you assisgn me please i can fix this issue easily ?
