### ISSUE TITLE
[DOCS] Center the images in `linking-issue-with-pr.md`

### ISSUE THREAD

**Issue by Pradumnasaraf** [Pradumnasaraf/open-source-with-pradumna#135]
### Description

Link to the docs. - https://github.com/Pradumnasaraf/open-source-with-pradumna/blob/main/pages/How-to/guide/linking-issue-with-pr.md

### Screenshots

N/A

**Comment by yung-coder** [comment]
Hey i would like to work on this @Pradumnasaraf

**Comment by PriyanshuAhlawat** [comment]
@Pradumnasaraf created the pr🙂

**Comment by hemantwasthere** [comment]
Hey @Pradumnasaraf, I would like to work on this issue. Please assign it to me

**Comment by Pradumnasaraf** [comment]
> Hey i would like to work on this @Pradumnasaraf

Go ahead you can work on it @yung-coder

**Comment by yung-coder** [comment]
Thanks @Pradumnasaraf 🙏
