### ISSUE TITLE
[DOCS] Center the images in the `reviewing-pr.md` docs

### ISSUE THREAD

**Issue by Pradumnasaraf** [Pradumnasaraf/open-source-with-pradumna#136]
### Description

Link to docs - https://github.com/Pradumnasaraf/open-source-with-pradumna/blob/main/pages/How-to/guide/reviewing-pr.md

### Screenshots

N/A

**Comment by kakkarot0** [comment]
hey can i work on this issue

**Comment by Vishrut19** [comment]
Hey can I work or help in this issue ?

**Comment by PriyanshuAhlawat** [comment]
@Pradumnasaraf  created pr

**Comment by hemantwasthere** [comment]
Hey @Pradumnasaraf, I would like to work on this issue. Please assign it to me

**Comment by Pradumnasaraf** [comment]
> hey can i work on this issue

Go ahead you can work on it @kakkarot0

**Comment by Vishrut19** [comment]
Hey @Pradumnasaraf can i also help @kakkarot0 in this issue ?

**Comment by Pradumnasaraf** [comment]
> Hey @Pradumnasaraf can i also help @kakkarot0 in this issue ?

You can work on other issues

**Comment by Vishrut19** [comment]
okay I have asked you on other issues too but I didn't get any response

**Comment by Pradumnasaraf** [comment]
> okay I have asked you on other issues too but I didn't get any response

Looks at the issues which are not assigned and drop a comment I will assign it to you, do fast :)

**Comment by Vishrut19** [comment]
okay
