### ISSUE TITLE
[DOCS] Add ALT attribute to the images in `adding-pr-template.md` docs 

### ISSUE THREAD

**Issue by Pradumnasaraf** [Pradumnasaraf/open-source-with-pradumna#137]
### Description

Link to doc - https://github.com/Pradumnasaraf/open-source-with-pradumna/blob/main/pages/How-to/guide/adding-pr-template.md

### Screenshots

N/A

**Comment by anujchourasia15** [comment]
Hey, I would love to work on this.

**Comment by anujchourasia15** [comment]
Hey, I would love to work on this.

**Comment by kakkarot0** [comment]
i would like to work on this issue

**Comment by Pradumnasaraf** [comment]
> Hey, I would love to work on this.

Go ahead you can work on it @anujchourasia15
