### ISSUE TITLE
[DOCS] Improve ALT text in `assigning-issue.md`

### ISSUE THREAD

**Issue by Pradumnasaraf** [Pradumnasaraf/open-source-with-pradumna#138]
### Description

Link to docs - https://github.com/Pradumnasaraf/open-source-with-pradumna/blob/main/pages/How-to/guide/assigning-issue.md

### Screenshots

N/A

**Comment by kakkarot0** [comment]
hey can i work in this issue

**Comment by YashPimple** [comment]
@Pradumnasaraf would like to work on this issue!

**Comment by tarund2302** [comment]
Hi, I would like to work on this issue.

**Comment by Vishrut19** [comment]
Hey @Pradumnasaraf Can I work on this issue ?

**Comment by hemantwasthere** [comment]
Hey @Pradumnasaraf , I would like to work on this issue. Please assign it to me
