### ISSUE TITLE
[DOCS] Add process/guide - "How to assign an issue to someone"

### ISSUE THREAD

**Issue by Pradumnasaraf** [Pradumnasaraf/open-source-with-pradumna#14]
### Changes/Action required
 
 - Add a complete process of **" How to assign an issue to someone"**, steps will contain a text, screenshot, Video (it can be a screen recording to show the steps), and GIF (if needed)
 
- Path of the file in which **steps** need to be added - [`open-source-with-pradumna/pages/How-to/guide/assigning-issue.md`](https://github.com/Pradumnasaraf/open-source-with-pradumna/blob/main/pages/How-to/guide/assigning-issue.md)

---

If you have any suggestions feel free to Open an [Issue](https://github.com/Pradumnasaraf/open-source-with-pradumna/issues)

#### This addition of the documentation will get added and hyperlinked in [`How-to/README.md`](https://github.com/Pradumnasaraf/open-source-with-pradumna/tree/main/pages/How-to) and also get hosted on the website https://Opensource.pradumnasaraf.co

<br>

![Screenshot from 2022-05-15 14-11-21](https://user-images.githubusercontent.com/51878265/168464628-905b0a25-627b-4560-b8e4-bd09940d8c7b.png)

**Comment by KendallDoesCoding** [comment]
I would like to work on this

**Comment by Prudence97** [comment]
Hello, 
If this is not taken. I would love to take it up. 

Also can I use a pictorial guide?

**Comment by Prudence97** [comment]
😂😊I just read through the docs. You said a picture guide etc can be added.

I would love to work on this.

**Comment by Pradumnasaraf** [comment]
Thank you for your interest!. Yes you can work on that. :smile: 

Let me know if you have any doubt.

**Comment by Prudence97** [comment]
Okay ☺️Thank you. I'll be sending a feedback soon.

**Comment by Pradumnasaraf** [comment]
Hey, @Prudence97  just a slight nudge, waiting for your PR :)

**Comment by Prudence97** [comment]
Hello @Pradumnasaraf  apologies for the delay. I'll get it across soon.

**Comment by Pradumnasaraf** [comment]
> Hello @Pradumnasaraf apologies for the delay. I'll get it across soon.

Take your time, I was just checking if you haven't caught up with any issues. 

If you need any help, feel free to ping me!. Again thank you for your effort

**Comment by Pradumnasaraf** [comment]
Hey, @Prudence97 can you please clarify whether you are working on this issue or not?
Thank you!!

**Comment by Prudence97** [comment]
I already sent a pull request. I think I merged it after waiting for a week or so.

Please check and confirm

**Comment by Pradumnasaraf** [comment]
Hey! there is no Pull Request from your side, you can check the page here [assigning-issue.md](https://github.com/Pradumnasaraf/open-source-with-pradumna/blob/main/pages/How-to/guide/assigning-issue.md)

**Comment by Prudence97** [comment]
I just saw it🤦 apparently, I didn't merge it right.

**Comment by Prudence97** [comment]
I've sent a pull request

**Comment by Pradumnasaraf** [comment]
> I've sent a pull request

No there is no PR, check you might have created it on your repo itself.

**Comment by Prudence97** [comment]
Have you seen it?

**Comment by singh-saksham** [comment]
Hey is the issue still open? Although I just started GitHub I would love to contribute to the best of my abilities.

**Comment by Prudence97** [comment]
Hi, It's still open. I was suppose to report to Pradumna earlier. I've been a bit busy and also trying to make out time to fix the corrections. 

It'll be nice if you can help @singh-saksham also, if you need my assistance I'll be ready to help.
I think Pradumna would also address you when he's online.

**Comment by singh-saksham** [comment]
@Prudence97 Thank you for your response. I don't know how to help you exactly. You can say that it's my first day properly using GitHub. I will be really thankful if you can provide essential tips or methods to contribute to this issue.

**Comment by singh-saksham** [comment]
@Pradumnasaraf I am trying to open the Twitter thread but it's redirecting me to a Github page only.

**Comment by Prudence97** [comment]
https://twitter.com/pradumna_saraf/status/1527840632018030597?t=U0wctEIvzeFkXH9NoUJiGw&s=19


👆🏽That's @Pradumnasaraf twitter page. Maybe you can find what you're looking for there

**Comment by singh-saksham** [comment]
@Prudence97 Thanks for the help

**Comment by Pradumnasaraf** [comment]
Hey @Prudence97  PR is already opened from your side can you do the changes suggested https://github.com/Pradumnasaraf/open-source-with-pradumna/pull/71

**Comment by Pradumnasaraf** [comment]
Hey @singh-saksham the PR is already opened for this issue. Can you please work on some other issues opened.

**Comment by Prudence97** [comment]
Hii @Pradumnasaraf  long time. I'm sorry I didn't respond to the previous messages. I've been trying to manage a product I built and I've been pretty busy. Hope you're great?

**Comment by Prudence97** [comment]
Also @Pradumnasaraf I think if I can have two more weeks I can look into it and make changes within that time period. 

I was also thinking @singh-saksham could look Into it if you wanted it to be cleared urgently

**Comment by singh-saksham** [comment]
> Hey @singh-saksham the PR is already opened for this issue. Can you please work on some other issues? May be this one #13

@Pradumnasaraf OK I will look into it. 👍

**Comment by aryanraj2713** [comment]
I can contribute😊

**Comment by Pradumnasaraf** [comment]
> I can contributeblush


Hey, thank you for your interest the PR is already open for this issue. I will be people some more issues in 1 or days. Keep an eye on that :)
