### ISSUE TITLE
[DOCS] Add process/guide - "How to clone a repo"

### ISSUE THREAD

**Issue by Pradumnasaraf** [Pradumnasaraf/open-source-with-pradumna#15]
### Changes/Action required
 
 - Add a complete process of **"How to clone a repo"**, steps will contain a text, screenshot, Video (it can be a screen recording to show the steps), and GIF (if needed)
 
- Path of the file in which **steps** need to be added - [`open-source-with-pradumna/pages/How-to/guide/cloning-repo.md`](https://github.com/Pradumnasaraf/open-source-with-pradumna/blob/main/pages/How-to/guide/cloning-repo.md)

---

If you have any suggestions feel free to Open an [Issue](https://github.com/Pradumnasaraf/open-source-with-pradumna/issues)

#### This addition of the documentation will get added and hyperlinked in [`How-to/README.md`](https://github.com/Pradumnasaraf/open-source-with-pradumna/tree/main/pages/How-to) and also get hosted on the website https://Opensource.pradumnasaraf.co

![Screenshot from 2022-05-15 14-11-21](https://user-images.githubusercontent.com/51878265/168464628-905b0a25-627b-4560-b8e4-bd09940d8c7b.png)

**Comment by 1Harshini** [comment]
Hey Pradumnasaraf 
can I work on this issue to add required text , screenshots and links

**Comment by Pradumnasaraf** [comment]
> Hey Pradumnasaraf can I work on this issue to add required text , screenshots and links

Yes, go ahead thank you!!

**Comment by Pradumnasaraf** [comment]
> hey Pradumna, you have a spelling mistake in this issue on the changes/action. You wrote chnages instead of changes

Thanks Akebu, Fixed it

**Comment by KendallDoesCoding** [comment]
@Pradumnasaraf This is in git right, according to me, only if you know how GitHub works you will use git, correct me if i'm wrong, so this isn't required.

**Comment by Pradumnasaraf** [comment]
> @Pradumnasaraf This is in git right, according to me, only if you know how GitHub works you will use git, correct me if i'm wrong, so this isn't required.

Yes!

**Comment by unnikrishnan2002** [comment]
I would like to work on this.

**Comment by Pradumnasaraf** [comment]
> I would like to work on this.

Thank you for your interest, Unni
