### ISSUE TITLE
[DOCS] Correct punctuation in Faq.md docs

### ISSUE THREAD

**Issue by anujchourasia15** [Pradumnasaraf/open-source-with-pradumna#150]
### Description

Link to doc - https://github.com/anujchourasia15/open-source-with-pradumna/blob/main/pages/Faq.md

### Screenshots

![issue](https://user-images.githubusercontent.com/75257120/193394162-2d445c32-5419-482a-944f-5764e9ce5e14.jpg)

**Comment by Pradumnasaraf** [comment]
Thank you for opening the issue

**Comment by hemantwasthere** [comment]
Hello @Pradumnasaraf, May I work on this issue

**Comment by VamshiReddy02** [comment]
Hey @Pradumnasaraf, I made a pull request on this issue. Please do check out.

**Comment by VamshiReddy02** [comment]
Hey @Pradumnasaraf, may I work on this issue? Sorry I made a PR without, you assigning me. because I'm new to open source contribution, now I read the contributing guideline and code of conduct. can you assign me this issue

**Comment by Pradumnasaraf** [comment]
Hey, @anujchourasia15 just for confirmation are you working on this issue? If not @VamshiReddy02 has already worked and they just re-open the closed PR.

**Comment by anujchourasia15** [comment]
No, I'm not working on this issue. @VamshiReddy02 can go ahead.

**Comment by yashdev9274** [comment]
is this issue already assigned?

**Comment by VamshiReddy02** [comment]
Hey @Pradumnasaraf, Can I go ahead with this issue?

**Comment by akebu6** [comment]
does this issue have anyone assigned to it yet?

**Comment by Pradumnasaraf** [comment]
> Hey @Pradumnasaraf, Can I go ahead with this issue?

Hey, yes. You can re-open the Close PR.

**Comment by Pradumnasaraf** [comment]
Hey, @anshrusia200 @akebu6 this issue is already assigned please look for some other issues.

**Comment by VamshiReddy02** [comment]
hey @Pradumnasaraf, I created a new PR for this issue. please do check out.
