### ISSUE TITLE
[BUG] Table Image margins not even

### ISSUE THREAD

**Issue by bloodmonk7** [Pradumnasaraf/open-source-with-pradumna#157]
### Description

Hey @Pradumnasaraf , The table does not contain image properly, there is margin difference on top as compared to bottom of it.
Can I work on it?

### Screenshots

![Screenshot 2022-10-01 141553](https://user-images.githubusercontent.com/48784848/193401325-763a79f5-b9e4-4430-98a2-5f5b2d8dfa82.png)

**Comment by Rinshin-Jalal** [comment]
I like to do this!

**Comment by bloodmonk7** [comment]
I will go to stylling part and look for padding given and will make the top and bottom padding of the picture equal so that the table border is perfectly even like left and right padding of picture
![Screenshot 2022-10-01 141553](https://user-images.githubusercontent.com/48784848/193437266-661079ea-ad3b-4fb5-acaa-4b0249158c67.png)

**Comment by Pradumnasaraf** [comment]
> I will go to stylling part and look for padding given and will make the top and bottom padding of the picture equal so that the table border is perfectly even like left and right padding of picture ![Screenshot 2022-10-01 141553](https://user-images.githubusercontent.com/48784848/193437266-661079ea-ad3b-4fb5-acaa-4b0249158c67.png)

It's a markdown table we can't add padding, I guess. That's why I asked what approach you will follow.
