### ISSUE TITLE
[DOCS] Add process/guide - "How to create a PR"

### ISSUE THREAD

**Issue by Pradumnasaraf** [Pradumnasaraf/open-source-with-pradumna#16]
### Changes/Action required
 
 - Add a complete process of **""How to create a PR""**, steps will contain a text, screenshot, Video (it can be a screen recording to show the steps), and GIF (if needed)
 
- Path of the file in which **steps** need to be added - [`open-source-with-pradumna/pages/How-to/guide/creating-pr.md`](https://github.com/Pradumnasaraf/open-source-with-pradumna/blob/main/pages/How-to/guide/creating-pr.md)

---

If you have any suggestions feel free to Open an [Issue](https://github.com/Pradumnasaraf/open-source-with-pradumna/issues)

#### This addition of the documentation will get added and hyperlinked in [`How-to/README.md`](https://github.com/Pradumnasaraf/open-source-with-pradumna/tree/main/pages/How-to) and also get hosted on the website https://Opensource.pradumnasaraf.co

![Screenshot from 2022-05-15 14-11-21](https://user-images.githubusercontent.com/51878265/168464628-905b0a25-627b-4560-b8e4-bd09940d8c7b.png)

**Comment by gullapalli9482** [comment]
I would like to take up this issue.

**Comment by Pradumnasaraf** [comment]
> I would like to take up this issue.

Thank you for your interest. Go ahead you can work on it, I have assigned the issue to you!!

**Comment by Pradumnasaraf** [comment]
Hey, @gullapalli9482  just a slight nudge, waiting for your PR :)

**Comment by gullapalli9482** [comment]
Yep, it'll be coming in soon

**Comment by gullapalli9482** [comment]
Most of the writing part is done, left with creating the video, I'm doing it for the first time, so experiencing a couple of hiccups, at max, it will be done by this weekend, nothing after that.

**Comment by Pradumnasaraf** [comment]
> Most of the writing part is done, left with creating the video, I'm doing it for the first time, so experiencing a couple of hiccups, at max, it will be done by this weekend, nothing after that.

No worries you can take your time, feel free to ping me, if you need any kind of help

**Comment by gullapalli9482** [comment]
Sure 👍🏼.

**Comment by gullapalli9482** [comment]
I think this issue can be closed now

**Comment by Pradumnasaraf** [comment]
Thank you for pointing it you, it should auto close. Anyways closing it with https://github.com/Pradumnasaraf/open-source-with-pradumna/pull/56
