### ISSUE TITLE
[BUG] Remove the paypal option from Funding.yaml

### ISSUE THREAD

**Issue by Pradumnasaraf** [Pradumnasaraf/open-source-with-pradumna#161]
#### Remove the PayPal option from FUNDING.yml

Link to the file - https://github.com/Pradumnasaraf/open-source-with-pradumna/blob/main/.github/FUNDING.yml

### Screenshots

![Screenshot from 2022-10-02 09-10-28](https://user-images.githubusercontent.com/51878265/193436901-9d461ad8-3b60-4d46-97aa-f4094b99ae6e.png)

**Comment by yung-coder** [comment]
Hey @Pradumnasaraf i would like to work on this...

**Comment by Pradumnasaraf** [comment]
> Hey @Pradumnasaraf i would like to work on this...

Hey, it's an begginer friendly issue, leave it for some other new contributors.

**Comment by yung-coder** [comment]
Okay np @Pradumnasaraf 👍

**Comment by grraghav120** [comment]
I would like to work on this...

**Comment by Pradumnasaraf** [comment]
> Hii @Pradumnasaraf I would like to work on this...

Go ahaed

**Comment by grraghav120** [comment]
okay working!! @Pradumnasaraf
