### ISSUE TITLE
[DOCS] Add process/guide - "How to delete a repo"

### ISSUE THREAD

**Issue by prnvtripathi** [Pradumnasaraf/open-source-with-pradumna#163]
### Hey @Pradumnasaraf  
I was looking through the OSWP website and I found that the <a href="https://oswp.study/#/pages/How-to/guide/delete-repo"> this</a> page shows work in progress.

### Screenshots

![image](https://user-images.githubusercontent.com/111558974/193437415-eb9b74e7-89a0-4cdd-a1ed-581ea89bc268.png)

**Comment by prnvtripathi** [comment]
I would like to work on this issue.

**Comment by Pradumnasaraf** [comment]
Hey, thank you for reporting. The file is there, but the naming is wrong. Here is the [file](https://github.com/Pradumnasaraf/open-source-with-pradumna/blob/main/pages/How-to/guide/delete-the-repo.md)

A patch will release soon. It will fix that name. Thank you

**Comment by prnvtripathi** [comment]
That's fine sir 💯
