### ISSUE TITLE
[DOCS] Add process/guide - "How to link and issue no with a PR"

### ISSUE THREAD

**Issue by Pradumnasaraf** [Pradumnasaraf/open-source-with-pradumna#17]
### Changes/Action required
 
 - Add a complete process of **"How to link and issue no with a PR"**, steps will contain a text, screenshot, Video (it can be a screen recording to show the steps), and GIF (if needed)
 
- Path of the file in which **steps** need to be added - [`open-source-with-pradumna/pages/How-to/guide/linking-issue-with-pr.md`](https://github.com/Pradumnasaraf/open-source-with-pradumna/blob/main/pages/How-to/guide/linking-issue-with-pr.md)

---

If you have any suggestions feel free to Open an [Issue](https://github.com/Pradumnasaraf/open-source-with-pradumna/issues)

#### This addition of the documentation will get added and hyperlinked in [`How-to/README.md`](https://github.com/Pradumnasaraf/open-source-with-pradumna/tree/main/pages/How-to) and also get hosted on the website https://Opensource.pradumnasaraf.co

![Screenshot from 2022-05-15 14-11-21](https://user-images.githubusercontent.com/51878265/168464628-905b0a25-627b-4560-b8e4-bd09940d8c7b.png)

#### This addition of the documentation will get added and hyperlinked in [`How-to/README.md`](https://github.com/Pradumnasaraf/open-source-with-pradumna/tree/main/pages/How-to) and also get hosted on the website https://Opensource.pradumnasaraf.co

![Screenshot from 2022-05-15 14-11-21](https://user-images.githubusercontent.com/51878265/168464628-905b0a25-627b-4560-b8e4-bd09940d8c7b.png)

**Comment by frazie** [comment]
I'd like to assist in this documentation.

**Comment by Pradumnasaraf** [comment]
Hey, @frazie just a slight nudge, waiting for your PR :)

**Comment by Pradumnasaraf** [comment]
Hey, @frazie can you please clarify whether you are working on this?
Thank you!

**Comment by Pradumnasaraf** [comment]
> Hi **@Pradumnasaraf,** I'd like to take this if **@frazie** is not updating on it

Thank you for the interest, sure go ahead!!

**Comment by frazie** [comment]
Kindly assign the task to @heykush 

sorry @Pradumnasaraf for the late dedication to the project, my work and study got ahead of me beyond my expectation. Hope I'll get t work with you more soon!!

**Comment by Pradumnasaraf** [comment]
> Kindly assign the task to @heykush
> 
> sorry @Pradumnasaraf for the late dedication to the project, my work and study got ahead of me beyond my expectation. Hope I'll get t work with you more soon!!

No worries @frazie, take your time, repo is always welcome for your contributions :)

**Comment by heykush** [comment]
Hi **@Pradumnasaraf** can we **connect** somewhere? I have a few queries.

**Comment by Pradumnasaraf** [comment]
> Hi **@Pradumnasaraf** can we **connect** somewhere? I have a few queries.

Hey!
Yes, you can open up a discussion on GitHub [here](https://github.com/Pradumnasaraf/open-source-with-pradumna/discussions) with your questions.
