### ISSUE TITLE
[DOCS] updating Regular content

### ISSUE THREAD

**Issue by lingeshwaran05** [Pradumnasaraf/open-source-with-pradumna#174]
### Description

updating your github tip from twitter and convert it into images with poet.so and attach it into regular updates page

### Screenshots

![image](https://user-images.githubusercontent.com/76167753/193496653-4926318d-6642-4695-8799-bf7ff93a29a8.png)

**Comment by lingeshwaran05** [comment]
can you please assign it to me

**Comment by Pradumnasaraf** [comment]
> can you please assign it to me

Yes go ahead make sure it is date wise :)

**Comment by lingeshwaran05** [comment]
Hey , I have finished this task yesterday itself , please checkout #176 pr and please include hacktoberfestaccepted label , 
Thanks,

If you want to make new page with docker tips and open source tips let me know

**Comment by lingeshwaran05** [comment]
Hey , now the page is successfully updated upto oct 4 , Thankyou
