### ISSUE TITLE
[DOCS] Link the License and Contributing.md to ReadMe

### ISSUE THREAD

**Issue by krupalitrivedi** [Pradumnasaraf/open-source-with-pradumna#175]
### Description

Hello! 

I believe it is a healthy choice to link the contribution guidelines and License to the end of the ReadMe files which can help people who are browsing through the repo navigate easily between files. 

If this issue sounds genuine, it can be a good first issue and be solved in following way. 

Steps:
- `Fork` the repo 
- Either clone the repo or go to the fork on GitHub
- Click on `edit` (the pencil button) and move to the end of the file 
- Add headings for Contributing Guidelines and License
- Add relevant sentences like "The project is licensed under (name of licence)" and "please check out the contributing guidelines before making a pull request"
- next you have to link them, use `[ ]( )` with the word to be used as hyperlink in square bracket and put `./LICENSE` and `./CONTRIBUTING.md` for license and contributing guidelines respectively.
- and you are done!

**Comment by shashankbhatgs** [comment]
@krupalitrivedi I would like to work on this issue. Can I?

**Comment by shashankbhatgs** [comment]
@saloni137 I thought of working on this issue since nobody was assigned :(

**Comment by saloni137** [comment]
@shashankbhatgs But I already did :)

**Comment by shashankbhatgs** [comment]
> @shashankbhatgs But I already did :)

@saloni137 you should ask the maintainers to assign it first and then work on it

**Comment by saloni137** [comment]
I don't think so that's how open source work @shashankbhatgs

**Comment by Pradumnasaraf** [comment]
Hey @krupalitrivedi, thank you for opening the issue. 

We discussed this previously to add them. The reason why we are not adding this to the README is that we use root README for hosting. Also, in the hosted webpage we don't need that and to keep the webpage short. 

Would love to hear your thoughts on this, TY again :)

**Comment by Pradumnasaraf** [comment]
Hey @saloni137, @shashankbhatgs is 100% correct. There are some guidelines, and that's how most of the repo functions. You can also check the [**contributing guidelines**](https://github.com/Pradumnasaraf/open-source-with-pradumna/blob/main/CONTRIBUTING.md) for that.

**Comment by Pradumnasaraf** [comment]
Closing this issue, feel free open another one. Thank you for your suggestions.
