### ISSUE TITLE
[DOCS] Add process/guide - "How to create issue (templates edition)"

### ISSUE THREAD

**Issue by Pradumnasaraf** [Pradumnasaraf/open-source-with-pradumna#18]
### Changes/Action required
 
 - Add a complete process of **"How to create issue templates"**, steps will contain a text, screenshot, Video (it can be a screen recording to show the steps), and GIF (if needed)
 
- Path of the file in which **steps** need to be added - [`open-source-with-pradumna/pages/How-to/guide/raise-issue-template.md`](https://github.com/Pradumnasaraf/open-source-with-pradumna/blob/main/pages/How-to/guide/raise-issue-template.md)

---

If you have any suggestions feel free to Open an [Issue](https://github.com/Pradumnasaraf/open-source-with-pradumna/issues)

#### This addition of the documentation will get added and hyperlinked in [`How-to/README.md`](https://github.com/Pradumnasaraf/open-source-with-pradumna/tree/main/pages/How-to) and also get hosted on the website https://Opensource.pradumnasaraf.co

![Screenshot from 2022-05-15 14-11-21](https://user-images.githubusercontent.com/51878265/168464628-905b0a25-627b-4560-b8e4-bd09940d8c7b.png)

**Comment by KendallDoesCoding** [comment]
I would like to work on this

**Comment by karnatisrinivas** [comment]
Hello @Pradumnasaraf , Can I add this guide?

**Comment by Pradumnasaraf** [comment]
> Hello @Pradumnasaraf , Can I add this guide?

Yes Srinivas, go ahead, Thank you for your interest!. :smile:

**Comment by Kanika637** [comment]
Hey @karnatisrinivas , are you still working on this?

**Comment by Kanika637** [comment]
Hey @Pradumnasaraf , can I work on this?

**Comment by Pradumnasaraf** [comment]
> Hey @Pradumnasaraf , can I work on this?
> 
Hey, Kanika thank you so much for your interest. Yes, sure you can work on this.

If you have doubts feel free to reach, feel free to ping me :)

**Comment by Kanika637** [comment]
Hey @Pradumnasaraf , could you please assign me this issue so that I can make the PR, as I have completed the work.

**Comment by Pradumnasaraf** [comment]
> Hey @Pradumnasaraf , could you please assign me this issue so that I can make the PR, as I have completed the work.

oh, so sorry I missed out on that. Assigned it to you 

**Side note** - You can create PR even if the issue is not assigned but you already commented and got the permission to work on it :)

**Comment by Kanika637** [comment]
Thanks @Pradumnasaraf , I have made the PR.
