### ISSUE TITLE
docs: Add process for "how to create a repository" 

### ISSUE THREAD

**Issue by prnvtripathi** [Pradumnasaraf/open-source-with-pradumna#181]
### Description

Hi @Pradumnasaraf, in the [how-to](https://oswp.study/#/pages/How-to/README) section of the website, if we can add how to create a repo, then it'll be easy to just refer to this page in future guides or processes which include creating a repository.

**Comment by Pradumnasaraf** [comment]
You just stole my mind and idea, haha. Yes, we need it. Do you want to contribute to that?

**Comment by prnvtripathi** [comment]
Ofcourse, i would love to :)

**Comment by Nymphalys** [comment]
I would like to work on this issue ,Can you assign me this issue?

**Comment by johnwinifred** [comment]
I would love to work on this issue

**Comment by Atharv-777** [comment]
hey @prnvtripathi are you still working on it?

**Comment by prnvtripathi** [comment]
Yeah, I've been working on it, just waiting for @Pradumnasaraf to assign the issue to me. So I can raise a PR

**Comment by Pradumnasaraf** [comment]
And to other commenters, try finding some other issue. Thank you

**Comment by prnvtripathi** [comment]
Hi @Pradumnasaraf, i made a pr referencing the issue then realised that it wasn't assigned to me. What should I do?
