### ISSUE TITLE
[DOCS] Update create-license.md

### ISSUE THREAD

**Issue by ShubhamJagtap2000** [Pradumnasaraf/open-source-with-pradumna#182]
### Description

I regularly follow your repo updates and look over whatever info is added. I can see an irregular structure of numbers in create-license.md for points no. 5, 6, and 7. Every point should start in a new line. (shown in the screenshot below)

I would also like to make a `table of licenses and a short description of it` that is included in the YouTube video link mentioned in the file so that one could easily understand which license does what and for details video is better. It will also enhance the quality of documentation.

Should I continue??

### Screenshots

![image](https://user-images.githubusercontent.com/63872951/193875494-85c9106a-cea2-4398-924b-5a6917b0b71b.png)

**Comment by Pradumnasaraf** [comment]
Thank you so much for following up on the update. I am just merging PR with RAW content and improving it over time with the contributions, that's my plan. In this way, more people can contribute.

Go ahead you can do the changes, thank you!
