### ISSUE TITLE
[FEATURE] UI improvement in Sidebar

### ISSUE THREAD

**Issue by Maaz-Code** [Pradumnasaraf/open-source-with-pradumna#183]
### Description

I would like to add a UI change to the Sidebar where when we are on a page then the corresponding text on Sidebar gets bold. This will give a better look to the Sidebar and help depict the highlighted page. I am also thinking of a way to give the Pages text a new look so that it becomes less confusing.

### Screenshots

![image](https://user-images.githubusercontent.com/65590762/193904191-2bd903e6-982a-4262-9522-f675904d0199.png)

**Comment by Notchoaveragejoe** [comment]
Can I help with this issue?

**Comment by Maaz-Code** [comment]
I am working on this already!

**Comment by Maaz-Code** [comment]
Ohh okay, then thanks for letting me know!
