### ISSUE TITLE
[OTHER] <description> I just wanna suggest you there is same opening of website after clicking on Github and Stars. 

### ISSUE THREAD

**Issue by shubham21155102** [Pradumnasaraf/open-source-with-pradumna#188]
### What would you like to share?

 I just wanna suggest you there is same opening of website after clicking on Github and Stars.
and i just want to write that in a better way.

**Comment by Pradumnasaraf** [comment]
> ### What would you like to share?
> I just wanna suggest you there is same opening of website after clicking on Github and Stars. and i just want to write that in a better way.

Sorry didn't get you. Can you explain a little more clearly with screenshots?

**Comment by Pradumnasaraf** [comment]
There is no response from your side, feel free to open with more details.
