### ISSUE TITLE
[DOCS] Typo and grammatical errors in README.md of How-to

### ISSUE THREAD

**Issue by getRicha** [Pradumnasaraf/open-source-with-pradumna#190]
### Description

There are some notable grammatical errors present in the README.md file of pages/How-to.

### Screenshots

<img width="562" alt="image" src="https://user-images.githubusercontent.com/74401402/194374256-bc448064-6d37-4832-a944-ff28905f4153.png">

**Comment by jainpatel25** [comment]
> ### Description
> There are some notable grammatical errors present in the README.md file of pages/How-to.
> 
> ### Screenshots
> <img alt="image" width="562" src="https://user-images.githubusercontent.com/74401402/194374256-bc448064-6d37-4832-a944-ff28905f4153.png">

can I resolve grammatical error
