### ISSUE TITLE
[DOCS] Adding "How to sign commits" in How To section

### ISSUE THREAD

**Issue by priyanshu68** [Pradumnasaraf/open-source-with-pradumna#193]
### Description

Hey @Pradumnasaraf ,in the [how-to](https://oswp.study/#/pages/How-to/README) section of the website, I would like to add how to sign commits, as it is a lesser known piece of information that gets necessary in open source.

**Comment by Pradumnasaraf** [comment]
Hey, thanks for opening the issue. This is a great topic to be added.

Some instructions: 

- Here is the image link which you can add to the How to section table.
`https://user-images.githubusercontent.com/51878265/194722406-73e2a603-c360-48dd-88bb-232abc170e81.png`

> Image Preview

![How to process img (1)](https://user-images.githubusercontent.com/51878265/194722406-73e2a603-c360-48dd-88bb-232abc170e81.png)


- When you create the markdown (in  https://github.com/Pradumnasaraf/open-source-with-pradumna/tree/main/pages/How-to), name it `sign-commits.md` 


If you have doubts feel free to ping me.

**Comment by Hyperbolic007** [comment]
@Pradumnasaraf do we want this in website or in repo??

**Comment by adityyaa-10** [comment]
Hi, can I work on this issue?

**Comment by priyanshu68** [comment]
@Pradumnasaraf you didn't assigned the issue , i just noticed it now, Can you please assign this to me?

**Comment by Pradumnasaraf** [comment]
> @Pradumnasaraf you didn't assign the issue , I just noticed it now, Can you please assign this to me as i have the pr ready for this issue?

Done
