### ISSUE TITLE
[DOCS] Adding 'Renaming a Repository' in the How To section

### ISSUE THREAD

**Issue by nexi9** [Pradumnasaraf/open-source-with-pradumna#194]
### Description

Hi! @Pradumnasaraf, I wanted to add a piece of useful info on how to rename a repository in the how-to section of your website, as it can be a life-saver for a lot of beginners. 

Kindly assign me this issue if you feel like this will work. Thanks in advance!

**Comment by Pradumnasaraf** [comment]
Hey, thanks for opening the issue. This is a great topic to be added.

Some instructions: 

- Here is the image link which you can add to the How to section table.
`https://user-images.githubusercontent.com/51878265/194721906-86e2acba-194e-4dcc-8886-17f6b729a4c6.png`

> Image Preview

![How to process img](https://user-images.githubusercontent.com/51878265/194721906-86e2acba-194e-4dcc-8886-17f6b729a4c6.png)

- When you create the markdown (in  https://github.com/Pradumnasaraf/open-source-with-pradumna/tree/main/pages/How-to), name it `rename-repo.md` 


If you have doubts feel free to ping me.

**Comment by hariomchaudhary123** [comment]
@Pradumnasaraf Can I contribute to this?

**Comment by nexi9** [comment]
@hariomchaudhary123 hey, I'm already about to push my pr
