### ISSUE TITLE
[FEATURE] Add dark/light theme toggler

### ISSUE THREAD

**Issue by vikasganiga05** [Pradumnasaraf/open-source-with-pradumna#197]
### Description

This is for adding a toggle button to switch between light and dark themes. There is a simple docsify plugin to do that :point_down: 

[:first_quarter_moon:docsify-darklight-theme](https://github.com/boopathikumar018/docsify-darklight-theme) - It is a simple and highly customizable theme for docsify.js. Using this theme, documents will have a theme switcher to switch between `dark-mode` and `light-mode`. See [preview](https://docsify-darklight-theme.boopathikumar.me) here.

I like to work on this issue. I already implemented this feature here &rarr; **[journey-book](https://collab-community.github.io/journey-book/)**
Thank You :pray:

**Comment by Pradumnasaraf** [comment]
For months I was planning to do that. Thank you so much for the issue.

**Comment by vikasganiga05** [comment]
> For months I was planning to add that feature. Thank you so much for the issue. Feel free to go ahead

Thanks! for assigning this issue to me. I will start working on it as soon as possible.
