### ISSUE TITLE
Add hover over open buttons.

### ISSUE THREAD

**Issue by Atharv181** [Pradumnasaraf/open-source-with-pradumna#199]
### Description

We can add hover effects on open button.

### Screenshots

![image](https://user-images.githubusercontent.com/73999654/194717515-eb7a3d97-cf89-49c7-b009-2a7209bbe544.png)

**Comment by Pradumnasaraf** [comment]
This is markdown and we use templates to host them, so hover can't be added. Thank you

**Comment by Atharv181** [comment]
Ok Thank you.
