### ISSUE TITLE
[DOCS] Add process/guide - "How to review a PR"

### ISSUE THREAD

**Issue by Pradumnasaraf** [Pradumnasaraf/open-source-with-pradumna#20]
### Changes/Action required
 
 - Add a complete process of **"How to review a PR"**, steps will contain a text, screenshot, Video (it can be a screen recording to show the steps), and GIF (if needed)
 
- Path of the file in which **steps** need to be added - [`open-source-with-pradumna/pages/How-to/guide/reviewing-pr.md`](https://github.com/Pradumnasaraf/open-source-with-pradumna/blob/main/pages/How-to/guide/reviewing-pr.md)

---

If you have any suggestions feel free to Open an [Issue](https://github.com/Pradumnasaraf/open-source-with-pradumna/issues)

#### This addition of the documentation will get added and hyperlinked in [`How-to/README.md`](https://github.com/Pradumnasaraf/open-source-with-pradumna/tree/main/pages/How-to) and also get hosted on the website https://Opensource.pradumnasaraf.co

![Screenshot from 2022-05-15 14-11-21](https://user-images.githubusercontent.com/51878265/168464628-905b0a25-627b-4560-b8e4-bd09940d8c7b.png)

**Comment by KendallDoesCoding** [comment]
I would like to work on this

**Comment by KendallDoesCoding** [comment]
Can I be assigned? I would like to work on this @Pradumnasaraf

**Comment by Pradumnasaraf** [comment]
> Can I be assigned? I would like to work on this @Pradumnasaraf

Hey! Kendal, you are already worked on some issues, we can leave them for the others and people new to the Open Source. Hope thing is understandable :smile:

**Comment by KendallDoesCoding** [comment]
> > Can I be assigned? I would like to work on this @Pradumnasaraf
> 
> Hey! Kendal, you are already worked on some issues, we can leave them for the others and people new to the Open Source. Hope thing is understandable 😄

fair enough, but I want to contribute as well.

**Comment by Jai-Solania-29** [comment]
Hey @Pradumnasaraf I would love to work on this issue 😃.

**Comment by Pradumnasaraf** [comment]
> Hey @Pradumnasaraf I would love to work on this issue smiley.

Thank you for your interest, go ahead you can work on it

**Comment by Jai-Solania-29** [comment]
Ok thank you Pradumna 😃

**Comment by Pradumnasaraf** [comment]
Hey waiting for your PR. If you have any doubts feel free to ping me!

**Comment by Jai-Solania-29** [comment]
Hey @Pradumnasaraf I'll push my changes tonight or may be by tomorrow. Actually I was busy in my exams.

**Comment by Jai-Solania-29** [comment]
Hey @Pradumnasaraf I have made the PR.
