### ISSUE TITLE
[DOCS] Update social-preview.md

### ISSUE THREAD

**Issue by ShubhamJagtap2000** [Pradumnasaraf/open-source-with-pradumna#200]
### Description

As social preview only works for Public repositories, I wanted to add it in the "Tips" section of social-preview.md as a point. Should I raise a PR?

**Comment by Pradumnasaraf** [comment]
> ### Description
> As social preview only works for Public repositories, I wanted to add it in the "Tips" section of social-preview.md as a point. Should I raise a PR?
> 
> ### Screenshots
> _No response_

Thank you for the Issue. I think that is understandable because the private repo is not shareable so having a social preview doesn't matter.

**Comment by ShubhamJagtap2000** [comment]
> > ### Description
> > As social preview only works for Public repositories, I wanted to add it in the "Tips" section of social-preview.md as a point. Should I raise a PR?
> > ### Screenshots
> > _No response_
> 
> Thank you for the Issue. I think that is understandable because the private repo is not shareable so having a social preview doesn't matter.

I am laughing to myself. PR obsession. Lol.
