### ISSUE TITLE
[DOCS] Align image to center in `starting-discussion.md`

### ISSUE THREAD

**Issue by ShubhamJagtap2000** [Pradumnasaraf/open-source-with-pradumna#201]
### Description

I can align the images in this [file](https://github.com/Pradumnasaraf/open-source-with-pradumna/blob/main/pages/How-to/guide/starting-discussion.md) as well as make them more proper with tools to look better.

**Comment by Pradumnasaraf** [comment]
Hey, thank you for opening the issue. I request you let other contributors contribute toward this issue.

**Comment by Vishrut19** [comment]
I want to take this task @Pradumnasaraf

**Comment by imran1509** [comment]
Is it completed?
Hey Pradumna Can I work on this? can you assign this to me?

**Comment by Pradumnasaraf** [comment]
Hey, @imran1509 sorry I forget to close this issue. It is already fixed. I will soon open some more issues

**Comment by imran1509** [comment]
Its okay.
