### ISSUE TITLE
add contributers images in readme file

### ISSUE THREAD

**Issue by Ankurrawat-12** [Pradumnasaraf/open-source-with-pradumna#202]
### Description

the images of the contributors to this repo will be shown in readme file

### Screenshots

![image](https://user-images.githubusercontent.com/78417225/194750400-21d3766c-68f9-4464-bb20-b545c3ba3ce8.png)

**Comment by Beast71421** [comment]
can i have this issue.

**Comment by Beast71421** [comment]
and can you please add hacktoberfest , hacktoberfest-accepted label

**Comment by Beast71421** [comment]
Done

**Comment by Pradumnasaraf** [comment]
Thank you for raising the issue, but we don't need that as it hosted README.

Also, you shouldn't have raised the pr without confirmation.
