### ISSUE TITLE
[BUG] Images not showing up

### ISSUE THREAD

**Issue by prakhartiwari0** [Pradumnasaraf/open-source-with-pradumna#204]
### Description

The images in [How to Create a PR](https://oswp.study/#/pages/How-to/guide/creating-pr) And [How to Raise an issue Basic](https://oswp.study/#/pages/How-to/guide/rasing-issue) are not showing up.

## How to create a PR page screenshot
![image](https://user-images.githubusercontent.com/65062036/194761590-df2522c4-55e3-49ef-bd6d-353f4834938a.png)

## How to raise an issue page screenshot
![image](https://user-images.githubusercontent.com/65062036/194761599-5ccd31d6-b71f-43e0-ab1b-8b87c4403ca5.png)

**Comment by Pradumnasaraf** [comment]
Woooh, thank you so much for the issue. That was a huge bug, after the recent image syntax change to markdown some pages are working and some are not, that's weird.

I have fixed that issue on high priority - https://github.com/Pradumnasaraf/open-source-with-pradumna/commit/3427ddc600d1e1e8b11a223c46c788a49ad4d9bb

Thank you again. Have a look again, if you find something else let us know

**Comment by prakhartiwari0** [comment]
I am glad to help you @Pradumnasaraf
Looking forward to contributing more!
