### ISSUE TITLE
[BUG] There are two issues in `create-project-board.md`

### ISSUE THREAD

**Issue by vikasganiga05** [Pradumnasaraf/open-source-with-pradumna#206]
### Description

There are two issues in `pages/How-to/guide/create-project-board.md` file.
1. Typo in the subheading.
2. The contributor added a video that is not rendered. So, convert the video into a gif and then add it. Also, add a subheading `Complete demo (GIF)` above the gif.

> Here is the gif which is converted from the video :point_down: 

![create-project-board](https://user-images.githubusercontent.com/74750414/194795088-4329f7e6-0a3c-4beb-b468-43f0672d7c52.gif)

### Screenshots

> Typo in subheading :point_down: 

![image](https://user-images.githubusercontent.com/74750414/194792974-e11712f9-295c-4227-af81-bc72f486eb85.png)

> The video is not rendered :point_down: 

![image](https://user-images.githubusercontent.com/74750414/194793069-77133304-a887-474f-94b7-f4191f6ac3c4.png)

**Comment by Pradumnasaraf** [comment]
> Hey @Pradumnasaraf , Can I work on the bug?

Hey, When you asked for it, then you have to wait for it. Also, you shouldn't have raised the PR without confirmation, and that's the repo guidelines too.

Hey, @vikasganiga05 will you work on this?

**Comment by saivardhankodimela** [comment]
@Pradumnasaraf  Sorry for the violation. This was my first contribution. I was curious and started working and figured the bug. so I was trying to explore github's feature, I accidentally raised the PR. I tried to undo it but coudn't. Hope you understand. :)

**Comment by vikasganiga05** [comment]
> > Hey @Pradumnasaraf , Can I work on the bug?
> 
> Hey, When you asked for it, then you have to wait for it. Also, you shouldn't have raised the PR without confirmation, and that's the repo guidelines too.
> 
> Hey, @vikasganiga05 will you work on this?

Hi Pradumna, @saivardhankodimela already made these changes and created a PR #207
