### ISSUE TITLE
[FEATURE] responsive navbar

### ISSUE THREAD

**Issue by E-fais** [Pradumnasaraf/open-source-with-pradumna#208]
### Description

Navbar is not looking good in small devices.
A hamburger menu will be much better.
Please assign me this issue, I would love to work on it.
![5897C71B-800A-4C30-993D-3FDF89F3618A](https://user-images.githubusercontent.com/102040088/195039562-821f9398-6e73-449c-9566-35ddc1855f54.png)

**Comment by Pradumnasaraf** [comment]
Hey, we use a template for the website. That means we don't use the styling file.  I think we can't fix that

**Comment by vikasganiga05** [comment]
It can be fixed using the custom stylesheet.
- Create a stylesheet file `style.css` on the root of the project.
- Link the stylesheet in the `index.html` file.
```html
<link rel="stylesheet" href="style.css" />
```
- Add the styles to fix this issue to the `style.css` file.

Done :+1:

**Comment by E-fais** [comment]
> Hey, we use a template for the website. That means we don't use the styling file. I think we can't fix that
So let me close the issue ;) 
Btw,  Can you please tell me about that template, so that i can use it for my next project.

**Comment by E-fais** [comment]
> It can be fixed using the custom stylesheet.
> 
> * Create a stylesheet file `style.css` on the root of the project.
> * Link the stylesheet in the `index.html` file. Make sure to add this below the default stylesheet of docsify.
> 
> ```
> <link rel="stylesheet" href="style.css" />
> ```
> 
> * Add the styles to fix this issue to the `style.css` file.
> 
> Done 👍

I am not sure about that ;)

**Comment by Pradumnasaraf** [comment]
> It can be fixed using the custom stylesheet.
> 
> * Create a stylesheet file `style.css` on the root of the project.
> * Link the stylesheet in the `index.html` file. Make sure to add this below the default stylesheet of docsify.
> 
> ```
> <link rel="stylesheet" href="style.css" />
> ```
> 
> * Add the styles to fix this issue to the `style.css` file.
> 
> Done +1

Thank you, Vikash for the info. I need to look into that. But for now we are good with the template one.
