### ISSUE TITLE
[DOCS] Add process/guide - "How to start a github discussion"

### ISSUE THREAD

**Issue by Pradumnasaraf** [Pradumnasaraf/open-source-with-pradumna#21]
### Changes/Action required
 
 - Add a complete process of **"How to start a github discussion"**, steps will contain a text, screenshot, Video (it can be a screen recording to show the steps), and GIF (if needed)
 
- Path of the file in which **steps** need to be added - [`open-source-with-pradumna/pages/How-to/guide/starting-discussion.md`](https://github.com/Pradumnasaraf/open-source-with-pradumna/blob/main/pages/How-to/guide/starting-discussion.md)

---

If you have any suggestions feel free to Open an [Issue](https://github.com/Pradumnasaraf/open-source-with-pradumna/issues)

#### This addition of the documentation will get added and hyperlinked in [`How-to/README.md`](https://github.com/Pradumnasaraf/open-source-with-pradumna/tree/main/pages/How-to) and also get hosted on the website https://Opensource.pradumnasaraf.co

![Screenshot from 2022-05-15 14-11-21](https://user-images.githubusercontent.com/51878265/168464628-905b0a25-627b-4560-b8e4-bd09940d8c7b.png)

**Comment by KendallDoesCoding** [comment]
I would like to work on this

**Comment by KendallDoesCoding** [comment]
@Pradumnasaraf Do you want to include text for how to enable discussions in repos or do you only want a guide for how to start a discussion for users?

**Comment by KendallDoesCoding** [comment]
> > @Pradumnasaraf Do you want to include text for how to enable discussions in repos or do you only want a guide for how to start a discussion for users?
> 
> this one is for how to **"start a GitHub discussion"**

Ok thanks, Just wanted to make sure.

**Comment by KendallDoesCoding** [comment]
I would love to work on this.
