### ISSUE TITLE
[FEATURE] Make navbar sticky along with the name

### ISSUE THREAD

**Issue by pritipsingh** [Pradumnasaraf/open-source-with-pradumna#213]
### Description

![image](https://user-images.githubusercontent.com/85965351/195288224-de4c4c13-f747-4c0f-a78d-daef0007c8e6.png)
Make this part sticky and also make the "Open Source with Pradumna" as part of the navBar.

Reference: 
![image](https://user-images.githubusercontent.com/85965351/195288540-ad69b20f-5be6-4c68-8bf3-1db1127f0f1d.png)

**Comment by pritipsingh** [comment]
@Pradumnasaraf can you check this out and let me know if I can work on this

**Comment by Pradumnasaraf** [comment]
Hey, thanks for opening the issue.

we use a custom template (No style sheet), so I think we can't do that. Let me know your thoughts.

**Comment by beauty108** [comment]
@Pradumnasaraf Inspite of being a custom template I still can fix it.

But for this I need you to add an extra CSS file in your repository.
 
Here is the result : )

![Screenshot 2022-10-15 012714](https://user-images.githubusercontent.com/111839696/195931556-5f3951c5-4f1e-4755-b437-322d7d8bbb88.png)

If you want this to be done then please assign this to me ASAP with a new CSS file.
Thankyou : )

**Comment by beauty108** [comment]
@Pradumnasaraf Above was in dark mode.

If you don't want to add a CSS file, still this can be done but the HTML file will be a little bit lengthy.

Below is in light mode : )

![Screenshot 2022-10-15 015840](https://user-images.githubusercontent.com/111839696/195938167-1a10b072-ac7b-4e22-821a-780cafcc3c89.png)

**Comment by beauty108** [comment]
@Pradumnasaraf Assign this issue to me ASAP so that I can create a pull request for the same. I have made all the required changes : )

**Comment by Pradumnasaraf** [comment]
Hey @beauty108, thank you for the interest, but for now we will keep at the stock template, due to less maintainability

**Comment by Pradumnasaraf** [comment]
Hey @beauty108, thank you for the interest, but for now we will keep at the stock template, due to less maintainability
