### ISSUE TITLE
[DOCS]  Adding "How  to create a new  Branch"

### ISSUE THREAD

**Issue by hemant-sw** [Pradumnasaraf/open-source-with-pradumna#216]
### Description

Hi ! @Pradumnasaraf  in  [How to](https://oswp.study/#/pages/How-to/README) section of OSWP's site . It would be great if we add how  to checkout to new branch or Existing branch then it will be very helpful for beginners . 

I can work on that issue if you think  this can be added. Thanks .

**Comment by Pradumnasaraf** [comment]
Hey, thanks for opening the issue. This is a great topic to be added.

Some instructions: 

- Here is the image link which you can add to the How to section table.
`https://user-images.githubusercontent.com/51878265/195896447-42001878-e09e-4ac2-a79e-203b5cbaeeb4.png`

> Image Preview

![How to process img](https://user-images.githubusercontent.com/51878265/195896447-42001878-e09e-4ac2-a79e-203b5cbaeeb4.png)

- When you create the markdown (in  https://github.com/Pradumnasaraf/open-source-with-pradumna/tree/main/pages/How-to), name it `create-branch.md` 

If you have doubts feel free to ping me.
