### ISSUE TITLE
Would be great if this repo has Documentation on Hacktoberfest too

### ISSUE THREAD

**Issue by 12rashic** [Pradumnasaraf/open-source-with-pradumna#218]
### Description

This repo has almost everything a begginer needs to get started on opensource journey , but it would be more perfect if it holds documentation on "Hacktoberfest" as its "hacktoberfest accepting  repo".
I would like to add this , Kindly assign it to me if this sounds good.
Thank you.

**Comment by Radiosnack** [comment]
Hey ! I can add good documnetation on hacktoberfest .... you can assign this to me :)

**Comment by Pradumnasaraf** [comment]
Hey, @12rashic, thank you for opening the Issue. Can you please clarify where you want to add those docs?

**Comment by 12rashic** [comment]
In the Github folder would like to add for a .MD file .Kindly let me know if it sounds good for contributing to repo.

**Comment by Pradumnasaraf** [comment]
> In the Github folder would like to add for a .MD file .Kindly let me know if it sounds good for contributing to repo.

I think for now we don't need this. Thank you
