### ISSUE TITLE
[DOCS] Typos and minor fixes

### ISSUE THREAD

**Issue by ayushrtwt** [Pradumnasaraf/open-source-with-pradumna#219]
### Description

There are some typos and minor fixes in the repo navigation section.

### Screenshots

![image](https://user-images.githubusercontent.com/102406757/195972187-57bdaa0a-52f5-486b-92cb-46753b7e3aa4.png)

**Comment by ayushrtwt** [comment]
I want to work on this issue @Pradumnasaraf. Please assign this to me.

**Comment by Pradumnasaraf** [comment]
Thank you for now it looks good.
