### ISSUE TITLE
[FEATURE] Include a back-to-top arrow button in all the pages.

### ISSUE THREAD

**Issue by unnikrishnan2002** [Pradumnasaraf/open-source-with-pradumna#220]
### Description

In the website I saw that it is not very convenient to scroll all the way back to the top of the page in some sections. So I am proposing to create a back-to-top arrow button so that users can reach at the top of the page with just a click

### Screenshots

![image](https://user-images.githubusercontent.com/76985777/195976950-fb1e2bb4-9571-4b25-8f61-d89f3f93c664.png)

**Comment by unnikrishnan2002** [comment]
I would like to implement this feature

**Comment by Pradumnasaraf** [comment]
Hey, Uni. Thnaks for opening the issue, how you are planning to implement this feature (Approach)?

**Comment by Jasleen-001** [comment]
Hey ,if no one is working on this issue then please assign it to me

**Comment by tmsagarofficial** [comment]
@Pradumnasaraf HI again, Pls let me know if I can work on this. I'm asking this as I didn't see any update for a week.

**Comment by Pradumnasaraf** [comment]
Hey, how you ganna implement this? Can you share approach and samples

**Comment by tmsagarofficial** [comment]
@Pradumnasaraf HI again, Pls let me know if I can work on this.

**Comment by Pradumnasaraf** [comment]
> @Pradumnasaraf HI again, Pls let me know if I can work on this.

Yes, that's why I asked for the sample and approach from you :). Then we can proceed further.

**Comment by tmsagarofficial** [comment]
sorry, bro @Pradumnasaraf I didn't follow up. I will send u the necessary details by tonight

**Comment by tmsagarofficial** [comment]
I'm very sorry...I'm a bit too busy rn due to college work....pls assign it to someone else....i will come back when I can spare some time

**Comment by Pradumnasaraf** [comment]
Closing the issue, no response from the opener.
