### ISSUE TITLE
[DOCS] <description>

### ISSUE THREAD

**Issue by dilpreet-kaur11** [Pradumnasaraf/open-source-with-pradumna#222]

**Comment by dilpreet-kaur11** [comment]
I want to add more learning resources for git and GitHub. Please assign this to me.

**Comment by Pradumnasaraf** [comment]
Can you share what resources will you add?

**Comment by dilpreet-kaur11** [comment]
Geesforgeeks and freecodecamp tutorial  of git and GitHub

**Comment by Pradumnasaraf** [comment]
Hey, the current ones are pretty good and more than enough. Adding too many can be confusing for beginners.

Thank you for opening the issue.
