### ISSUE TITLE
[DOCS] How to review the PR by running it on our local system

### ISSUE THREAD

**Issue by klaus0512** [Pradumnasaraf/open-source-with-pradumna#223]
### Description

Sometimes a maintainer needs to check the RP by running it on his local system. So we can add this new feature to demonstrate, how someone can review the PR by taking the code on his local system.

**Comment by klaus0512** [comment]
Hey @Pradumnasaraf, do look at this issue.
Also, I want to work on this issue, do assign me.

**Comment by Pradumnasaraf** [comment]
Go ahead @klaus0512
