### ISSUE TITLE
[DOCS] Add ALT text and remove extra lines in `star-repo.md`

### ISSUE THREAD

**Issue by Pradumnasaraf** [Pradumnasaraf/open-source-with-pradumna#225]
### Description

Add the `alt` attribute in the images the [docs](https://github.com/Pradumnasaraf/open-source-with-pradumna/blob/main/pages/How-to/guide/star-repo.md). Also remove the extra line spacing.

**Comment by Atharv-777** [comment]
Hey @Pradumnasaraf can you assign me this task?

**Comment by Pradumnasaraf** [comment]
> Hey @Pradumnasaraf can you assign me this task?

Yes, go head. Thank you for your interest.

**Comment by guneet-01** [comment]
Hey @Pradumnasaraf plz assign me this issue
