### ISSUE TITLE
[FEATURE] Adding new file about template repository

### ISSUE THREAD

**Issue by ShubhamJagtap2000** [Pradumnasaraf/open-source-with-pradumna#227]
### Description

Hello @Pradumnasaraf , I observed that the information about "making a template repository" can be an addition to the open-source project. Why repo templates are used, explaining how to do it (with screenshots), and how they can be used for other repositories can make a good file to add in to the "how to" directory.

Should I start making this file, please assign me the task?

**Comment by Pradumnasaraf** [comment]
Hey, yes go ahead. Thank you

**Comment by ShubhamJagtap2000** [comment]
Thank you for assigning.
