### ISSUE TITLE
[DOCS] Add contribution guidelines

### ISSUE THREAD

**Issue by Pradumnasaraf** [Pradumnasaraf/open-source-with-pradumna#23]
The contribution guide should be sectioned and specific to [pages](https://github.com/Pradumnasaraf/open-source-with-pradumna/tree/main/pages).

If the pages have a similar pattern put them in one section,

**Comment by KendallDoesCoding** [comment]
I would like to work on this @Pradumnasaraf

**Comment by Pradumnasaraf** [comment]
> I would like to work on this @Pradumnasaraf

Yes, you can work on it.

Please don't comment on every issue, you can only work on a single issue at a time.

**Comment by KendallDoesCoding** [comment]
> > I would like to work on this @Pradumnasaraf
> 
> Yes, you can work on it.
> 
> Please don't comment on every issue, you can only work on a single issue at a time.

Ok thanks.

Sorry

**Comment by Pradumnasaraf** [comment]
> > > I would like to work on this @Pradumnasaraf
> > 
> > Yes, you can work on it.
> > 
> > Please don't comment on every issue, you can only work on a single issue at a time.
> 
> Ok thanks.
> 
> Sorry

No worries I have added some details above, if you need any help feel free to ping me! 😀

**Comment by KendallDoesCoding** [comment]
> > > > I would like to work on this @Pradumnasaraf
> > > 
> > > 
> > > Yes, you can work on it.
> > > Please don't comment on every issue, you can only work on a single issue at a time.
> > 
> > 
> > Ok thanks.
> > Sorry
> 
> No worries I have added some details above, if you need any help feel free to ping me! 😀

This seems pretty hard, can I do #21 instead?

**Comment by Pradumnasaraf** [comment]
> > > > > I would like to work on this @Pradumnasaraf
> > > > 
> > > > 
> > > > Yes, you can work on it.
> > > > Please don't comment on every issue, you can only work on a single issue at a time.
> > > 
> > > 
> > > Ok thanks.
> > > Sorry
> > 
> > 
> > No worries I have added some details above, if you need any help feel free to ping me! grinning
> 
> This seems pretty hard, can I do #21 instead?

One thing you can do you can add basic stuff like life cloning and commands we will enhance, later on, hope that works for you?

**Comment by KendallDoesCoding** [comment]
> life cloning and commands we will enhance, later on,

sorry, I didn't understand, wdym by this?

**Comment by Pradumnasaraf** [comment]
> > life cloning and commands we will enhance, later on,
> 
> sorry, I didn't understand, wdym by this?

I mean you can create the basic structure of that, we can make it more robust later on

**Comment by KendallDoesCoding** [comment]
> > > life cloning and commands we will enhance, later on,
> > 
> > 
> > sorry, I didn't understand, wdym by this?
> 
> I mean you can create the basic structure of that, we can make it more robust later on

Ok gotcha, will try.

**Comment by KendallDoesCoding** [comment]
@Pradumnasaraf please review #27
