### ISSUE TITLE
[FEATURE] Add process and documentation about GitHub code spaces

### ISSUE THREAD

**Issue by prnvtripathi** [Pradumnasaraf/open-source-with-pradumna#234]
### Description

As GitHub came up with a new feature of code spaces, i would like to add it in the repo and let beginners know about it more clearly.

### Screenshots

![image](https://user-images.githubusercontent.com/111558974/205546025-da990cb8-6356-4539-9416-b66e7008f9bb.png)

**Comment by Pradumnasaraf** [comment]
Hey, thanks for opening the issue. Yes, go ahead

**Comment by Pradumnasaraf** [comment]
Hey,

You can name the file as `use-codespaces.md` and here is the image link - 
https://user-images.githubusercontent.com/51878265/206258171-df44aff5-92b2-4f7e-926b-ff1efd06af85.png

Preview:

![How to process img](https://user-images.githubusercontent.com/51878265/206258171-df44aff5-92b2-4f7e-926b-ff1efd06af85.png)

Let me know if you need any help
