### ISSUE TITLE
[DOCS] updating regular content page

### ISSUE THREAD

**Issue by lingeshwaran05** [Pradumnasaraf/open-source-with-pradumna#236]
### Description

Updating your GitHub tips in regular content page

### Screenshots

![image](https://user-images.githubusercontent.com/76167753/206886338-0004a02c-679a-40d6-8811-55b5b1f54a4e.png)

**Comment by Pradumnasaraf** [comment]
Hey, thanks for opening the issue. Would you like to update it?

**Comment by lingeshwaran05** [comment]
Yeah, I am working on this

**Comment by Pradumnasaraf** [comment]
Thank you!
