### ISSUE TITLE
[FEATURE] How about making this accesible on one page

### ISSUE THREAD

**Issue by alok-38** [Pradumnasaraf/open-source-with-pradumna#239]
### Description

I see that for each topic a separate blog page opens. How about making this accessible on one single page and add more interactive features.
I have not attempted to do that yet. I will keep you posted as and when I commence my project.

**Comment by Pradumnasaraf** [comment]
Thanks for opening the issue.

**Comment by hasnainmakada-99** [comment]
Hey @alok-38, can you please be more specific about this issue, because I'm interested

**Comment by alok-38** [comment]
@hasnainmakada-99 I think the website has been working as expected. Maybe I did not take note of it correctly.

https://user-images.githubusercontent.com/121376211/215330273-6f9ebde5-cd93-4611-babc-95c2c11dad73.mp4

**Comment by Pradumnasaraf** [comment]
Website working fine. Closing the issue
