### ISSUE TITLE
[FEATURE] I want to reduce the height of the button 

### ISSUE THREAD

**Issue by mohammadshaad** [Pradumnasaraf/open-source-with-pradumna#241]
### Description

I want to reduce the height of the "Open" button on the home page. Kindly assign me this issue.

### Screenshots

![image](https://user-images.githubusercontent.com/89409389/211161046-bed5855a-45c9-45e3-aa73-6f000a173348.png)

**Comment by mohammadshaad** [comment]
Because it is looking too big right now.

**Comment by Pradumnasaraf** [comment]
I think it's okay from an accessibility point of view. Thank you
