### ISSUE TITLE
[FEATURE] improve table of pages on mobile view

### ISSUE THREAD

**Issue by shyamtawli** [Pradumnasaraf/open-source-with-pradumna#244]
### Description

i can try converting table of pages into cards like view to in mobile view to look more attractive,
because on mobile view user have to scroll side wise to see open button.

card view will also look good on desktop mode also.

**Comment by Pradumnasaraf** [comment]
Hey,

Thanks for opening the Issue. It's based on Markdown how will you approach that?

**Comment by shyamtawli** [comment]
Sorry but i cant understand "based on markdown"?

**Comment by Pradumnasaraf** [comment]
I mean we render markdown as a website using Docsify. So. there is no actual code accept `index.html`

**Comment by shyamtawli** [comment]
Now i get it. let me learn and search about it and if i am able to do it, I will let you know.

**Comment by alok-38** [comment]
[Extended markdown syntax](https://www.markdownguide.org/extended-syntax/l) might be the way to go.
@Pradumnasaraf Could this issue be assigned to me or is @shyamtawli working on it?

**Comment by shyamtawli** [comment]
@alok-38 No Brother I am not.

**Comment by Pradumnasaraf** [comment]
This is on super low priority. Closing this one.
