### ISSUE TITLE
[OTHER] <Improvement in FAQ Section>

### ISSUE THREAD

**Issue by Mudit-Jxin7** [Pradumnasaraf/open-source-with-pradumna#253]
### What would you like to share?

I believe that implementing a dropdown FAQ would enhance the overall visual appeal and functionality compared to a conventional, static FAQ format

**Comment by Mudit-Jxin7** [comment]
I have created a PR for the same

**Comment by Pradumnasaraf** [comment]
I will keep it simple as it's also good for accessibility and screen readers. So closing this issue.
