### ISSUE TITLE
[DOCS] Error in documentation.

### ISSUE THREAD

**Issue by abuharish02** [Pradumnasaraf/open-source-with-pradumna#256]
### Description

There is an error in line no 78 in pages/Regular.md 

### Screenshots

![Screenshot 2023-06-30 115824](https://github.com/Pradumnasaraf/open-source-with-pradumna/assets/111338069/ad3c8915-4756-40c1-8673-f5dd6d9690c9)

**Comment by Pradumnasaraf** [comment]
Go ahead and fix it.

**Comment by PranavJoshi18** [comment]
Hey! May I fix this issue as no one has been assigned yet.

**Comment by Pradumnasaraf** [comment]
@PranavJoshi18 Do you want to make a PR on this? If yes, I will assign the issue to you

**Comment by Pradumnasaraf** [comment]
@abuharish02 would you like to contribute there is no answer from Pranav.

**Comment by abuharish02** [comment]
@Pradumnasaraf Let it be for new comers.

**Comment by Pradumnasaraf** [comment]
> @Pradumnasaraf Let it be for newcomers. 

I know I am just confirming before that as you open the issue.

**Comment by Marnin-A** [comment]
Hi, @Pradumnasaraf I'd like to work on this.

**Comment by Pradumnasaraf** [comment]
> Hi, @Pradumnasaraf I'd like to work on this.

Sure go ahead.
