### ISSUE TITLE
[BUG] Markdown format not properly rendered onto the main site

### ISSUE THREAD

**Issue by hasnainmakada-99** [Pradumnasaraf/open-source-with-pradumna#257]
### Description

I would like to request to the maintainers that I have found an issue inside the `os.pradumnasaraf.dev` 

Here's is the issue 👇🏻 

![image](https://github.com/Pradumnasaraf/open-source-with-pradumna/assets/82728823/ce213e1b-e7fd-4a93-9096-9fa68d4a2389)
 As you can clearly see from the above image the URL is not properly rendered as it is inside the README.md inside the github project

Here's the output of the rendered text inside the README.md file 👇🏻 

![image](https://github.com/Pradumnasaraf/open-source-with-pradumna/assets/82728823/3654f53e-c22f-4b61-a8ed-232d264f816a)

**Comment by Pradumnasaraf** [comment]
Yes, go ahead. Thank you

**Comment by Pradumnasaraf** [comment]
Also, If you like to fix this repo as well go ahead :) https://github.com/Pradumnasaraf/DevOps

**Comment by hasnainmakada-99** [comment]
> Also, If you like to fix this repo as well go ahead :) https://github.com/Pradumnasaraf/DevOps (If you wish to contribute, create the PR directly)

Sure pradumna

**Comment by Pradumnasaraf** [comment]
Closes #258
