### ISSUE TITLE
[DOCS] Update `Regular.md`

### ISSUE THREAD

**Issue by Pradumnasaraf** [Pradumnasaraf/open-source-with-pradumna#260]
### Description

Update `Regular.md` with the Tweet Posted after 17 Feb 2023 on https://twitter.com/pradumna_saraf about Git and GitHub. For example, look at https://github.com/Pradumnasaraf/open-source-with-pradumna/blob/main/pages/Regular.md. 

### Screenshots

<img width="1501" alt="Screenshot 2023-07-06 at 1 16 12 AM" src="https://github.com/Pradumnasaraf/open-source-with-pradumna/assets/51878265/e4caf695-f72f-42ce-b364-31f00ac81ec5">

**Comment by KshitizRana** [comment]
May I work on this issue?
Please assign it to me.

**Comment by Pradumnasaraf** [comment]
Sure go ahead.

**Comment by KshitizRana** [comment]
Posts before 17 Feb 2023 are not visible.

**Comment by Pradumnasaraf** [comment]
> Posts before 17 Feb 2023 are not visible on https://github.com/Pradumnasaraf/open-source-with-pradumna/blob/main/pages/Regular.md

Not sure what you mean. I can see them

**Comment by Pradumnasaraf** [comment]
Closes #261
