### ISSUE TITLE
[DOCS] Update `Regular.md`

### ISSUE THREAD

**Issue by Pradumnasaraf** [Pradumnasaraf/open-source-with-pradumna#263]
### Description

Update `Regular.md` with the Tweet Posted after 25 Feb 2023 on https://twitter.com/pradumna_saraf about Git and GitHub. For example, look at https://github.com/Pradumnasaraf/open-source-with-pradumna/blob/main/pages/Regular.md. 

### Screenshots

<img width="1501" alt="Screenshot 2023-07-06 at 1 16 12 AM" src="https://github.com/Pradumnasaraf/open-source-with-pradumna/assets/51878265/e4caf695-f72f-42ce-b364-31f00ac81ec5">

**Comment by munnokd** [comment]
Hello, @Pradumnasaraf Can I work on this issue?

**Comment by Pradumnasaraf** [comment]
Yes, go ahead.

**Comment by Pradumnasaraf** [comment]
Are you still working on this issue?

**Comment by munnokd** [comment]
Yes I will complete this issue in next two days.

**Comment by munnokd** [comment]
Hello, @Pradumnasaraf  I am getting an error on [poet.so](https://poet.so/) screenshot I provided below so if any solution of this is possible so provide me.
![image](https://github.com/Pradumnasaraf/open-source-with-pradumna/assets/81804004/31e09096-1ba7-4f02-b3ab-f56adeeff739)

**Comment by Pradumnasaraf** [comment]
> Hello, @Pradumnasaraf  I am getting an error on [poet.so](https://poet.so/) screenshot I provided below so if any solution of this is possible so provide me.
> ![image](https://github.com/Pradumnasaraf/open-source-with-pradumna/assets/81804004/31e09096-1ba7-4f02-b3ab-f56adeeff739)
> 

Ah, thanks to Elon.
Try this: https://10015.io/tools/tweet-to-image-converter

**Comment by munnokd** [comment]
Hey, @Pradumnasaraf I created pr on this issue please review my pr and say me if any changes need.
