### ISSUE TITLE
[DOCS] Incorrect date in `Regular.md`

### ISSUE THREAD

**Issue by Marnin-A** [Pradumnasaraf/open-source-with-pradumna#265]
### Description

In [Regular.md](https://github.com/Pradumnasaraf/open-source-with-pradumna/blob/main/pages/Regular.md) the tweet for 30th April was labeled with 30th May instead.

### Screenshots

![Regular-md-Issue](https://github.com/Pradumnasaraf/open-source-with-pradumna/assets/78488320/c0440f17-e23e-4d91-badb-e8bc037ee116)

**Comment by Marnin-A** [comment]
Hi @Pradumnasaraf  I'd like to fix this

**Comment by abhijeetgauravm** [comment]
I have made a pull request for the issue . Kindly review it @Pradumnasaraf !

**Comment by Pradumnasaraf** [comment]
> Hi @Pradumnasaraf I'd like to fix this

Yes, go ahead, Marnin.

**Comment by Pradumnasaraf** [comment]
> I have made a pull request for the issue . Kindly review it @Pradumnasaraf !

Read https://github.com/Pradumnasaraf/open-source-with-pradumna/blob/main/CONTRIBUTING.md. Get issue assigned the create a PR and on this issue, somebody already asked for it.
