### ISSUE TITLE
[DOCS] Adding docs about GitHub Gists

### ISSUE THREAD

**Issue by ShubhamJagtap2000** [Pradumnasaraf/open-source-with-pradumna#270]
### Description

Hello @Pradumnasaraf, 

I have been contributing to the open-source and DevOps repos for a long time. I recently found nothing has been added about GitHub Gists in the docs.

I want to add a .md file in which basic info about Github Gists, their need & usage will be documented. The file content will be easy to understand and the amount will normally be 1 page as the other files in the open-source repo.

Please, give your thoughts and give me a heads-up to raise a PR regarding the same.

Thank you!

**Comment by Pradumnasaraf** [comment]
Sure Go ahead and it in the "How to" section. Here is graphics for that

**Comment by ShubhamJagtap2000** [comment]
Sure @Pradumnasaraf , going to add the change, it is in progress. Thanks.
