### ISSUE TITLE
[BUG] <description>

### ISSUE THREAD

**Issue by prjailani** [Pradumnasaraf/open-source-with-pradumna#272]
### Description

Your twitter or X course link is not available or working. Pls fix it.

**Comment by Pradumnasaraf** [comment]
Hey, 

Thanks for reporting. Can you provide the page URL or screenshot? I am unable to find it

**Comment by prjailani** [comment]
Sorry. But today it is working fine. I don't know why. So I'll close the issue now.

**Comment by Pradumnasaraf** [comment]
Ah, no need to say sorry. Thank you again for raising the issue!
