### ISSUE TITLE
[DOCS] Add `Work In Progress` badge/banner to `How-to/guide/*.md`

### ISSUE THREAD

**Issue by vikasganiga05** [Pradumnasaraf/open-source-with-pradumna#28]
### Description

The [How-to guides](https://github.com/Pradumnasaraf/open-source-with-pradumna/tree/main/pages/How-to) are not completed right now. So, my suggestion is to add a badge/banner like the below one as a placeholder to every markdown files in `How-to/guide/` folder :point_down: 

### Badges

![Work In Progress](https://img.shields.io/badge/Markdown%20Guide-WIP-yellow)
![Work In Progress](https://img.shields.io/badge/Markdown%20Guide-WIP-yellow?style=flat-square)
![Work In Progress](https://img.shields.io/badge/Markdown%20Guide-WIP-yellow?style=for-the-badge)

### Banners

![github-header-image-1](https://user-images.githubusercontent.com/74750414/169188784-680014eb-ae5a-4062-b9c0-40276f28a261.png)

![github-header-image-2](https://user-images.githubusercontent.com/74750414/169188797-e8dc207e-25e3-4550-ae44-ff7dfd87033f.png)

---

I created the pattern for the WIP banner. You can use this pattern to create your own banner image :point_down: 

![bg-wip-pattern](https://user-images.githubusercontent.com/74750414/169189785-9ac95655-b4f2-4b2d-a03b-bae6c90fc6f9.png)

**Comment by Pradumnasaraf** [comment]
Banner looks wonderful @vikasganiga05, thank you for your effort and support!

**Comment by vikasganiga05** [comment]
Okay, I think the below banner will look good on the page :point_down: 

<img src="https://user-images.githubusercontent.com/74750414/169188784-680014eb-ae5a-4062-b9c0-40276f28a261.png" width="300" />

**Comment by Pradumnasaraf** [comment]
> Okay, I think the below banner will look good on the page :point_down: 
> 
> <img src="https://user-images.githubusercontent.com/74750414/169188784-680014eb-ae5a-4062-b9c0-40276f28a261.png" width="300" />

Go for it 🔥
