### ISSUE TITLE
Issue missing for adding-pr-template.md

### ISSUE THREAD

**Issue by KendallDoesCoding** [Pradumnasaraf/open-source-with-pradumna#34]
### Description

There is no issue created for adding-pr-template.md although, the icon says Work in Progress

Please create the issue at the earliest @Pradumnasaraf

**Comment by Pradumnasaraf** [comment]
Thanks for the issue, fixed in (#11)

**Comment by KendallDoesCoding** [comment]
> ### Description
> There is no issue created for adding-pr-template.md although, the icon says Work in Progress
> 
> Please create the issue at the earliest @Pradumnasaraf
> 
> ### Screenshots
> _No response_

Oops, there was a issue created, but a duplicate, instead of just 1. my bad
