### ISSUE TITLE
[FEATURE] Add a Git commands page Section

### ISSUE THREAD

**Issue by Pradumnasaraf** [Pradumnasaraf/open-source-with-pradumna#45]
### What would you like to share?

The section will include git command and its explanations

**Comment by Sreekar-Shodhan** [comment]
So this is about each and every git command and their simple explanation or most used git commands and their explanation? 
I would like to add few git commands if its okay.

**Comment by Pradumnasaraf** [comment]
Hey @Sreekar-Shodhan It's still in the planning stages, still not sure
Thank you for the interest.

**Comment by IMPranshu** [comment]
Some useful commands can be :
`git commit --amend`
`git branch --show-current`
`git push -f`

These commands really helped me a lot while making clean PRs. Maybe some details regarding them should be provided to efficiently use these commands.

**Comment by Pradumnasaraf** [comment]
Thank you @IMPranshu
