### ISSUE TITLE
[DOCS] Typos in main README.md

### ISSUE THREAD

**Issue by AliFahed** [Pradumnasaraf/open-source-with-pradumna#46]
### Description

I noticed there are **two typos** in the main README.md, LEARNING RESOURCES Section.
1. First typo is in the Description:
- Typo in keyword "open **souce**" is missing 'r' in "source".
2. Second typo is in the Page (Link- clickable):
- Typo in the naming of the link, "pages/**Resourses**" should be "pages/**Resources**".

### Screenshots

![typos_in_learning_resources_section](https://user-images.githubusercontent.com/90851899/170973899-1f9dd77c-c3c2-47f3-aaf3-ebeb935b945a.PNG)

**Comment by AliFahed** [comment]
Hey @Pradumnasaraf, I noticed these typos while learning from this amazing repo, this is my first ever issue. Please can you assign me for this issue, to make my first pull request :)

**Comment by Pradumnasaraf** [comment]
Hey @AliFahed , thank you for opening an issue, go ahead you can work on it.
