### ISSUE TITLE
Add some beginner-friendly repo

### ISSUE THREAD

**Issue by Susmita-Dey** [Pradumnasaraf/open-source-with-pradumna#49]
### Description

I wanna add some of my beginner-friendly repositories.

1. [Contribute-To-This-Project-First](https://github.com/opensourcecommunity-hub/Contribute-To-This-Project-First)
2. [developer-portfolios](https://github.com/opensourcecommunity-hub/developer-portfolios)
3. [join-the-community](https://github.com/opensourcecommunity-hub/join-the-community)
4. [amazing-github-projects-collection](https://github.com/opensourcecommunity-hub/amazing-github-projects-collection)
5. [amazing-github-profiles](https://github.com/opensourcecommunity-hub/amazing-github-profiles)
6. [Complete-Web-Development](https://github.com/opensourcecommunity-hub/Complete-Web-Development)

**Comment by KendallDoesCoding** [comment]
Can I add these repos in to the .md file @Pradumnasaraf

**Comment by Pradumnasaraf** [comment]
Hey, @Susmita-Dey thank you for opening the issue. In the above-listed projects, I can see there are some similar projects which are already there, and some require more beginner-friendly docs. I will have another look this weekend, Thank you
