### ISSUE TITLE
Add Favicon to the Website

### ISSUE THREAD

**Issue by Jai-Solania-29** [Pradumnasaraf/open-source-with-pradumna#59]
### Description

Right now Website doesn't have any Favicon.

### Screenshots

![Screenshot (95)](https://user-images.githubusercontent.com/90816300/173195173-4efe6358-0df5-4af0-ac5c-d16d7658cc5d.png)

**Comment by KendallDoesCoding** [comment]
I don't think adding a favicon is possible as this is hosted via GitHub Pages and the website runs on .md, but I'm unsure.

Please let me know @Pradumnasaraf

**Comment by Pradumnasaraf** [comment]
Hey! @Jai-Solania-29, thank you for opening the Issue, can you explain a little bit more about which icons and things you are suggesting to add, by providing a screenshot?

**Comment by KendallDoesCoding** [comment]
> Hey! @Jai-Solania-29, thank you for opening the Issue, can you explain a little bit more about which icons and things you are suggesting to add, by providing a screenshot?

We can add a "OSWP" or "OS" as the favicon which stands as "Open Source with @Pradumnasaraf" and "Open Source".

**Comment by Jai-Solania-29** [comment]
Hey Prdumna !
I want to add a Favicon to this Website and for that either we can use this given logo from your website ....

![Screenshot (96)](https://user-images.githubusercontent.com/90816300/173231688-94481a7b-a072-4d90-9cff-54ca2380cc70.png)

Or I can try to design a different logo that suits your Website, and then we can use it as a Favicon for the website.

**Comment by Pradumnasaraf** [comment]
> Hey Prdumna ! I want to add a Favicon to this Website and for that either we can use this given logo from your website ....
> 
> ![Screenshot (96)](https://user-images.githubusercontent.com/90816300/173231688-94481a7b-a072-4d90-9cff-54ca2380cc70.png)
> 
> Or I can try to design a different logo that suits your Website, and then we can use it as a Favicon for the website.

Okay, thank you for the info, We can use the use Open Source one (to which arrow is pointing) :)

**Comment by Jai-Solania-29** [comment]
Ok sure I'll add this.
