### ISSUE TITLE
[DOCS]Add process/guide - "How to create issue templates"

### ISSUE THREAD

**Issue by Pradumnasaraf** [Pradumnasaraf/open-source-with-pradumna#65]
### Changes/Action required
 
 - Add a complete process of **"How to create issue templates"**, steps will contain a text, screenshot, screen recording, and GIF (if needed)
 
- Path of the file in which **steps** need to be added - [`open-source-with-pradumna/pages/How-to/guide/adding-issue-template.md`](https://github.com/Pradumnasaraf/open-source-with-pradumna/blob/main/pages/How-to/guide/adding-issue-template.md)

---

If you have any suggestions feel free to Open an [Issue](https://github.com/Pradumnasaraf/open-source-with-pradumna/issues)

#### This addition of the documentation will get added and hyperlinked in [`How-to/README.md`](https://github.com/Pradumnasaraf/open-source-with-pradumna/tree/main/pages/How-to) and also get hosted on the website https://Opensource.pradumnasaraf.co

![Screenshot from 2022-05-15 14-11-21](https://user-images.githubusercontent.com/51878265/168464628-905b0a25-627b-4560-b8e4-bd09940d8c7b.png)

**Comment by code-hyker** [comment]
@Pradumnasaraf may I work on it?

**Comment by code-hyker** [comment]
@Pradumnasaraf are "raising an issue template" and "adding an issue template" different issues ? I am asking this because there is already an issue in which creating of an issue template has been shown with steps.Verify it once

**Comment by code-hyker** [comment]
https://github.com/Pradumnasaraf/open-source-with-pradumna/blob/main/pages/How-to/guide/raise-issue-template.md

**Comment by Pradumnasaraf** [comment]
Hey! both are different. 
This issue you are working on is about how to `create issue templates` and you mentioned is about how to `raise/create an issue through issue templates`.

For this issue, we will create the Markdown one [`docs`](https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/manually-creating-a-single-issue-template-for-your-repository)

Hope that is clear :)

**Comment by code-hyker** [comment]
Got it!

**Comment by Pradumnasaraf** [comment]
Hey waiting for your PR, if you have any doubts feel free to ping!

**Comment by code-hyker** [comment]
Sorry for the delay  due to exams! I will send the PR within a day or two.

**Comment by Pradumnasaraf** [comment]
Hey, this is the last call @code-hyker are you working on this issue?

**Comment by code-hyker** [comment]
Pardon me ! Kindly assign this issue to someone else.

**Comment by yash251** [comment]
I would like to work on this @Pradumnasaraf

**Comment by Pradumnasaraf** [comment]
> I would like to work on this @Pradumnasaraf

Go for it. Thank you!

**Comment by kartikgajjar7** [comment]
Hey @Pradumnasaraf  anyone working on this issue?if no ..I would like to work on this :)

**Comment by Pradumnasaraf** [comment]
Hey! @yash251 Are you still working on this issue?

**Comment by yash251** [comment]
Yes! I'll send pr In a day or two

**Comment by kartikgajjar7** [comment]
great 👍

**Comment by Pradumnasaraf** [comment]
Hey, @yash251 I have unassigned you the issue due, @kartikgajjar7 would you like to work on this?

**Comment by yash251** [comment]
Can you please reassign it? I will open PR after the 1st of October so that it can count towards your Hactoberfest contribution.

**Comment by Pradumnasaraf** [comment]
> Can you please reassign it? I will open PR after the 1st of October so that it can count towards your Hactoberfest contribution.

No worries, I have reassign it to you, Open PR after 1st

**Comment by Vishrut19** [comment]
Hey Can i also work on this ?

**Comment by Pradumnasaraf** [comment]
> Hey Can i also work on this ?

Go ahead I have assigned two issues to you :)

**Comment by Pradumnasaraf** [comment]
> Hey @Pradumnasaraf Can i also work on this ?

This issue is already assigned to @yash251
