### ISSUE TITLE
[DOCS] Add process/guide - "How to star a repo"

### ISSUE THREAD

**Issue by Pradumnasaraf** [Pradumnasaraf/open-source-with-pradumna#66]
### Changes/Action required
 
 - Add a complete process of **"How to star a repo"**, steps will contain a text, screenshot, screen recording, and GIF (if needed)
 
- Path of the file in which **steps** need to be added - [`open-source-with-pradumna/pages/How-to/guide/star-repo.md`](https://github.com/Pradumnasaraf/open-source-with-pradumna/blob/main/pages/How-to/guide/star-repo.md)

---

If you have any suggestions feel free to Open an [Issue](https://github.com/Pradumnasaraf/open-source-with-pradumna/issues)

#### This addition of the documentation will get added and hyperlinked in [`How-to/README.md`](https://github.com/Pradumnasaraf/open-source-with-pradumna/tree/main/pages/How-to) and also get hosted on the website https://Opensource.pradumnasaraf.co

![Screenshot from 2022-05-15 14-11-21](https://user-images.githubusercontent.com/51878265/168464628-905b0a25-627b-4560-b8e4-bd09940d8c7b.png)

**Comment by code-hyker** [comment]
@Pradumnasaraf may I work on this issue?

**Comment by Pradumnasaraf** [comment]
Hey! thank you for showing interest.

Small request, don't start working on any issue before you got any comments from the maintainers or it gets assigned to you.

**Comment by code-hyker** [comment]
Sure! Will take care of it from next time.
