### ISSUE TITLE
[DOCS] Add process/guide - "How to fork a repo"

### ISSUE THREAD

**Issue by Pradumnasaraf** [Pradumnasaraf/open-source-with-pradumna#67]
### Changes/Action required
 
 - Add a complete process of **"How to fork a repo"**, steps will contain a text, screenshot, screen recording, and GIF (if needed)
 
- Path of the file in which **steps** need to be added - [`open-source-with-pradumna/pages/How-to/guide/fork-repo.md`](https://github.com/Pradumnasaraf/open-source-with-pradumna/blob/main/pages/How-to/guide/fork-repo.md)

---

If you have any suggestions feel free to Open an [Issue](https://github.com/Pradumnasaraf/open-source-with-pradumna/issues)

#### This addition of the documentation will get added and hyperlinked in [`How-to/README.md`](https://github.com/Pradumnasaraf/open-source-with-pradumna/tree/main/pages/How-to) and also get hosted on the website https://Opensource.pradumnasaraf.co

![Screenshot from 2022-05-15 14-11-21](https://user-images.githubusercontent.com/51878265/168464628-905b0a25-627b-4560-b8e4-bd09940d8c7b.png)

**Comment by Sreekar-Shodhan** [comment]
Hey pradumnasaraf can you please  assign this issue to me , I will contribute on Sunday or Saturday night as I have exam tomorrow. 
Thank you

**Comment by Pradumnasaraf** [comment]
> Hey pradumnasaraf can you please assign this issue to me , I will contribute on Sunday or Saturday night as I have exam tomorrow. Thank you

Thank you Sreekar for your interest, sure you can work on this. 
No worries take your time Take your time :). If you have any issue, feel free to ping me

**Comment by Sreekar-Shodhan** [comment]
Yeah, thank you pradumna, really excited to make my first PR.

**Comment by Pradumnasaraf** [comment]
> 

WOW, great this is your PR. I am more than excited than you :)
Good Luck!!

**Comment by Sreekar-Shodhan** [comment]
Hey @Pradumnasaraf , I am done with the writing part but I am confused to add the screenshot part. Like If i take a screenshot and edit, save in my local computer and if I set it like ![alt text](home/open-source/ss/image)  will it be displayed the same after merging? Like How should I add the screenshot part?

**Comment by Sreekar-Shodhan** [comment]
![image](https://user-images.githubusercontent.com/71596539/174735561-70b2c42b-a36b-4c68-899f-32638fc5e631.png)

Is this correct?

**Comment by Pradumnasaraf** [comment]
Hey @Sreekar-Shodhan, its local path will not work, instead, you can generate `githubusercontent` link on Github and use that in docs.

you can generate link this:

https://user-images.githubusercontent.com/51878265/174975933-70964ac7-e6f8-4465-bb4a-8af961ab067a.mp4

**Comment by Sreekar-Shodhan** [comment]
Thanks pradumna, will try this and check soon.

**Comment by Sreekar-Shodhan** [comment]
Hey @Pradumnasaraf I have completed the writing part of fork-repo part but Iam confused on how to push it. 
Like I created the new branch in open-source-with-pradumnasaraf file. or should I create that branch in How-to file?

**Comment by Sreekar-Shodhan** [comment]
Sorry for being late, but my exams were completed yesterday.

**Comment by Sreekar-Shodhan** [comment]
Hey pradumna is everything alright with the PR? Please let me know if there any changes required in it.
