### ISSUE TITLE
[DOCS] Gramatical mistake in `How-to`

### ISSUE THREAD

**Issue by Sreekar-Shodhan** [Pradumnasaraf/open-source-with-pradumna#75]
### Description

In the Pages/How-to guide there are images like Create a PR etc 

Mistake in last two images, its Fork a repo instead of "an repo" and star a repo instead of "an repo"

Its a small thing but I found it as error so raising this issue.

### Screenshots

![image](https://user-images.githubusercontent.com/71596539/178463465-67ee9a29-93b9-4d0d-993c-648389c417d8.png)

**Comment by Pradumnasaraf** [comment]
Hey, thank you for pointing it out we will soon fix that.

**Comment by Pradumnasaraf** [comment]
Hey @kelvinparmar sorry for the late reply. Busy with my exams

Yes, go ahead. You can download both the corrected image here - https://www.canva.com/design/DAFAvDyVN04/h_Y6xD8kcXu1IBiwWV2r6Q/edit

**Comment by kelvinparmar** [comment]
How can I download it? I am not able to download it

**Comment by kelvinparmar** [comment]
It's just playing slide show

**Comment by singh-saksham** [comment]
@kelvinparmar Hey if you are still having trouble maybe I can help you. Please do contact me

**Comment by kelvinparmar** [comment]
How to download images?

**Comment by singh-saksham** [comment]
@kelvinparmar right click on the image and click Save as.

**Comment by kelvinparmar** [comment]
In that option not giving jpg format

**Comment by singh-saksham** [comment]
Try to screenshot it.

**Comment by kelvinparmar** [comment]
yeah I have done by that issue

**Comment by kelvinparmar** [comment]
Thanks for your reply

**Comment by Pradumnasaraf** [comment]
Hey @kelvinparmar 
Here are links for both. you can use the,
https://user-images.githubusercontent.com/51878265/182035398-d951c098-92cd-40a5-b435-fc91019bb289.png
https://user-images.githubusercontent.com/51878265/182035400-bab2b6a3-311b-41f2-9315-9841aceb1c2f.png

**Comment by Pradumnasaraf** [comment]
Closed in https://github.com/Pradumnasaraf/open-source-with-pradumna/commit/260723a5030b5fdf80ecfba46a349430c7ac8b3c
