### ISSUE TITLE
[DOCS] Typo & repeated words in the documentation

### ISSUE THREAD

**Issue by anieshak** [Pradumnasaraf/open-source-with-pradumna#84]
### Description

Hello Pradumna,
As you know, I am new to Open Source & learning how to contribute. I came across your instructions  on how to raise a bug but the below documentation contains typo which I have highlighted in brackets & below I have also shared the best way to communicate your intended message. 

--> When you click on (New Issue , you will get a list of 4 types of issues.)
-> If you find any bug in the repository feel free to click on _(Get Started')_ and you will get a template <in which you will get a template in which you will write a crisp title of the bug> and then in the description, **ellaborate** the bug.) 
-> (Try to add some screenshots of the bug so that it will be easy for the maintainer to understand and then react.) 

Solution -> **Below mentioned is a better way to communicate the same without any typos or repeated words -** 

--> When you click on 'New Issue', you are prompted with 4 types of issues - 

-> If you find any bug in the repository, feel free to click on 'Get Started' and you will get a template in which you write a crisp/short title of the bug. 
     In the 'Description' section, please elaborate the details of the bug you encountered.
-> In the 'Screenshots' section, please add some screenshots of the bug to make it easy for the maintainer to understand and        make necessary changes.

I hope you accept my suggestions & make necessary changes to the documentation.

Thanks,
Aniesh

### Screenshots

![image](https://user-images.githubusercontent.com/20052332/187727583-ba5619ab-6462-4949-9faf-1a00543cebbd.png)

![image](https://user-images.githubusercontent.com/20052332/187729062-729ea837-c5d1-4100-8ca2-0b08982f724d.png)

**Comment by anieshak** [comment]
@Pradumnasaraf  for visibility...

**Comment by Pradumnasaraf** [comment]
Thank you for opening the issue!

**Comment by ArpanBalpande** [comment]
Raised the PR: https://github.com/Pradumnasaraf/open-source-with-pradumna/pull/86
Please review. Thanks.
