### ISSUE TITLE
[DOCS] Add process/guide - "How to create delete a repo" 

### ISSUE THREAD

**Issue by Pradumnasaraf** [Pradumnasaraf/open-source-with-pradumna#92]
### Description

Hey! Contributor,

This issue is for adding the guide/process for **How we can delete a repo**. The step needs to be well defined and include the Screenshot/Screen recording for better explanation. To get an overview of how the docs should look, check the available docs [`here`](https://github.com/Pradumnasaraf/open-source-with-pradumna/blob/main/pages/How-to/guide)

- Path to the dedicate Markdown for this issue - [`open-source-with-pradumna/pages/How-to/guide/delete-repo.md`](https://github.com/Pradumnasaraf/open-source-with-pradumna/blob/main/pages/How-to/guide/delete-repo.md)

---

If you have any suggestions feel free to Open an [Issue](https://github.com/Pradumnasaraf/open-source-with-pradumna/issues)

**Also if you need any kind of help, feel free to ping!**

**Comment by YashPimple** [comment]
@Pradumnasaraf I would like to work on this could you assign it to me?

**Comment by trenz999** [comment]
I'm new to open-source but will get articles on how to delete repos.

**Comment by Pradumnasaraf** [comment]
Hey, @YashPimple thank you for your interest. Go ahead will the issue.

**Comment by Pradumnasaraf** [comment]
> I'm new to open-source but will get articles on how to delete repos.

Hey, you can have a look at other issues as someone is already interested prior to you, thank you!

**Comment by YashPimple** [comment]
@Pradumnasaraf do i need to create a specific branch ? and can you delete the [open-source-with-pradumna/pages/How-to/guide/delete-repo.md](https://github.com/Pradumnasaraf/open-source-with-pradumna/blob/main/pages/How-to/guide/delete-repo.md) from the main branch so that I can add my file?

**Comment by Pradumnasaraf** [comment]
> @Pradumnasaraf do i need to create a specific branch ? and can you delete the [open-source-with-pradumna/pages/How-to/guide/delete-repo.md](https://github.com/Pradumnasaraf/open-source-with-pradumna/blob/main/pages/How-to/guide/delete-repo.md) from the main branch so that I can add my file?

Didn't get your point. Jus make changes in your form it can be on the main as well as branch (Branch is more preferred) and raise a PR
