### ISSUE TITLE
[DOCS] Add process/guide - "How to add a social preview to a repo"

### ISSUE THREAD

**Issue by Pradumnasaraf** [Pradumnasaraf/open-source-with-pradumna#93]
### Description

Hey! Contributor,

This issue is for adding a guide/process for **How to add a social preview to a repo**. The step needs to be well defined and include the Screenshot/Screen recording for better explanation. To get an overview of how the docs should look, check the available docs [`here`](https://github.com/Pradumnasaraf/open-source-with-pradumna/blob/main/pages/How-to/guide)

- Path to the dedicate Markdown for this issue - [`open-source-with-pradumna/pages/How-to/guide/social-preview.md`](https://github.com/Pradumnasaraf/open-source-with-pradumna/blob/main/pages/How-to/guide/social-preview.md)

---

If you have any suggestions feel free to Open an [Issue](https://github.com/Pradumnasaraf/open-source-with-pradumna/issues)

**Also if you need any kind of help, feel free to ping!**

**Comment by AbbeyIT** [comment]
Hello @Pradumnasaraf can I work on this issue?

**Comment by Pradumnasaraf** [comment]
Hey, @AbbeyIT, thank you for your interest. Go ahead will the issue.
