### ISSUE TITLE
[DOCS] Add process/guide - "How to use GitHub Pages"

### ISSUE THREAD

**Issue by Pradumnasaraf** [Pradumnasaraf/open-source-with-pradumna#94]
### Description

Hey! Contributor,

This issue is for adding the guide/process for **How to use GitHub Pages**. The step needs to be well defined and include the Screenshot/Screen recording for better explanation. To get an overview of how the docs should look, check the available docs [`here`](https://github.com/Pradumnasaraf/open-source-with-pradumna/blob/main/pages/How-to/guide)

- Path to the dedicate Markdown for this issue - [`open-source-with-pradumna/pages/How-to/guide/github-pages.md`](https://github.com/Pradumnasaraf/open-source-with-pradumna/blob/main/pages/How-to/guide/github-pages.md)

---

If you have any suggestions feel free to Open an [Issue](https://github.com/Pradumnasaraf/open-source-with-pradumna/issues)

**Also if you need any kind of help, feel free to ping!**

**Comment by itzwow** [comment]
Hi @Pradumnasaraf  I would like to work on this issue.

**Comment by KlausMikhaelson** [comment]
Hey @Pradumnasaraf incase this issue is not resolved than would love to work on it since I used to make a lot of static pages back when I was a beginner and had faced some issues too so would love to document it so that others won't.

**Comment by Pradumnasaraf** [comment]
> Hi @Pradumnasaraf I would like to work on this issue.

Yes, go ahead. thank you!

**Comment by KlausMikhaelson** [comment]
Ooo got it thanks !

**Comment by prnvtripathi** [comment]
Hi @Pradumnasaraf, if the issue still persists can i work on this issue?

**Comment by Pradumnasaraf** [comment]
> Hi @Pradumnasaraf, if the issue still persists can i work on this issue?

Hey, @prnvtripathi yes go ahead, 

But, I will recommend opening PR after the 1st of October so that it can count towards your Hactoberfest contribution smile

**Comment by prnvtripathi** [comment]
> > Hi @Pradumnasaraf, if the issue still persists can i work on this issue?
> 
> Hey, @prnvtripathi yes go ahead,
> 
> But, I will recommend opening PR after the 1st of October so that it can count towards your Hactoberfest contribution.

will do the same :)
