### ISSUE TITLE
[DOCS] Add process/guide - "How to create GitHub secrets" 

### ISSUE THREAD

**Issue by Pradumnasaraf** [Pradumnasaraf/open-source-with-pradumna#95]
### Description

Hey! Contributor,

This issue is for adding a guide/process for **How to create GitHub secrets**. The step needs to be well defined and include the Screenshot/Screen recording for better explanation. To get an overview of how the docs should look, check the available docs [`here`](https://github.com/Pradumnasaraf/open-source-with-pradumna/blob/main/pages/How-to/guide)

- Path to the dedicate Markdown for this issue - [`open-source-with-pradumna/pages/How-to/guide/create-github-secret.md`](https://github.com/Pradumnasaraf/open-source-with-pradumna/blob/main/pages/How-to/guide/create-github-secret.md)

---

If you have any suggestions feel free to Open an [Issue](https://github.com/Pradumnasaraf/open-source-with-pradumna/issues)

**Also if you need any kind of help, feel free to ping!**

**Comment by hasnainmakada-99** [comment]
Hey @Pradumnasaraf  I would like to work on this issue

**Comment by Vishrut19** [comment]
Hey @Pradumnasaraf Can I work on this issue for Hacktoberfest ?

**Comment by Pradumnasaraf** [comment]
> Hey @Pradumnasaraf I would like to work on this issue

Yes go ahead

**Comment by prnvtripathi** [comment]
Hey, @hasnainmakada-99 , i wanted to know if you're still working on the issue, if not I would like to work on it.

**Comment by hasnainmakada-99** [comment]
> Hey, @hasnainmakada-99 , i wanted to know if you're still working on the issue, if not I would like to work on it.
> 

Yes @prnvtripathi I'm still working on it and will raise the pr by tomorrow

**Comment by prnvtripathi** [comment]
> Yes @prnvtripathi I'm still working on it and will raise the pr by tomorrow
Ok sir :)

**Comment by prnvtripathi** [comment]
> > Hey, @hasnainmakada-99 , i wanted to know if you're still working on the issue, if not I would like to work on it.
> 
> Yes @prnvtripathi I'm still working on it and will raise the pr by tomorrow

Ok sir :)
