### ISSUE TITLE
[DOCS] Add process/guide - "How to create a licence" 

### ISSUE THREAD

**Issue by Pradumnasaraf** [Pradumnasaraf/open-source-with-pradumna#96]
### Description

Hey! Contributor,

This issue is for adding the guide/process for **How to create a licence**. The step needs to be well defined and include the Screenshot/Screen recording for better explanation. To get an overview of how the docs should look, check the available docs [`here`](https://github.com/Pradumnasaraf/open-source-with-pradumna/blob/main/pages/How-to/guide)

- Path to the dedicate Markdown for this issue - [`open-source-with-pradumna/pages/How-to/guide/create-licence.md`](https://github.com/Pradumnasaraf/open-source-with-pradumna/blob/main/pages/How-to/guide/create-licence.md)

---

If you have any suggestions feel free to Open an [Issue](https://github.com/Pradumnasaraf/open-source-with-pradumna/issues)

**Also if you need any kind of help, feel free to ping!**

**Comment by Indira-kumar** [comment]
Hey @Pradumnasaraf  I would like to work on this issue

**Comment by Pradumnasaraf** [comment]
Hey, @Indira-kumar, thank you for your interest. Go ahead will the issue.

**Comment by Indira-kumar** [comment]
Thank you so much for the opportunity 🤍

**Comment by Pradumnasaraf** [comment]
Hey, @Indira-kumar are you still working on this issue?

**Comment by Indira-kumar** [comment]
Yes Sir, I am working on it, In sometime I will be done
Sorry for the delay

**Comment by Pradumnasaraf** [comment]
> Yes Sir, I am working on it, In sometime I will be done
> Sorry for the delay

Awesome, I will recommend opening PR after the 1st of October so that it can count towards your Hactoberfest contribution

**Comment by Indira-kumar** [comment]
Yes sir will do that. Thank you💛

**Comment by Harish2930** [comment]
Hey @Pradumnasaraf , is the issue still open? Can I contribute to the issue?
