### ISSUE TITLE
[DOCS] Add process/guide - "How to create a Releases"

### ISSUE THREAD

**Issue by Pradumnasaraf** [Pradumnasaraf/open-source-with-pradumna#98]
### Description

Hey! Contributor,

This issue is for adding the guide/process for **How to create a Releases - manually**. The step needs to be well defined and include the Screenshot/Screen recording for better explanation. To get an overview of how the docs should look, check the available docs [`here`](https://github.com/Pradumnasaraf/open-source-with-pradumna/blob/main/pages/How-to/guide)

- Path to the dedicate Markdown for this issue - [`open-source-with-pradumna/pages/How-to/guide/create-releases.md`](https://github.com/Pradumnasaraf/open-source-with-pradumna/blob/main/pages/How-to/guide/create-releases.md)

---

If you have any suggestions feel free to Open an [Issue](https://github.com/Pradumnasaraf/open-source-with-pradumna/issues)

**Also if you need any kind of help, feel free to ping!**

**Comment by hasnainmakada-99** [comment]
Hey @Pradumnasaraf I would like to work on this issue

**Comment by Pradumnasaraf** [comment]
Yes, go ahead @hasnainmakada-99. Thank you!

**Comment by hasnainmakada-99** [comment]
Hey @Pradumnasaraf will it be okay If I take references from official GitHub Docs?
