### ISSUE TITLE
[DOCS] Add process/guide - "How to create to create GitHub project board"

### ISSUE THREAD

**Issue by Pradumnasaraf** [Pradumnasaraf/open-source-with-pradumna#99]
### Description

Hey! Contributor,

This issue is for adding the guide/process for **How to create to create GitHub project board**. The step needs to be well defined and include the Screenshot/Screen recording for better explanation. To get an overview of how the docs should look, check the available docs [`here`](https://github.com/Pradumnasaraf/open-source-with-pradumna/blob/main/pages/How-to/guide)

- Path to the dedicate Markdown for this issue - [`open-source-with-pradumna/pages/How-to/guide/create-project-board.md`](https://github.com/Pradumnasaraf/open-source-with-pradumna/blob/main/pages/How-to/guide/create-project-board.md)

---

If you have any suggestions feel free to Open an [Issue](https://github.com/Pradumnasaraf/open-source-with-pradumna/issues)

**Also if you need any kind of help, feel free to ping!**

**Comment by kelvinparmar** [comment]
@Pradumnasaraf  please explain me what I have to do in this issue ?
1)Do I have to write the steps on how to create a repo for a project in GitHub?  OR
2)How to create a project for organization in GitHub or how to create a project for yourself?

what to do between the two?

**Comment by kelvinparmar** [comment]
[https://docs.github.com/en/issues/organizing-your-work-with-project-boards/managing-project-boards/creating-a-project-board](url)

**Comment by kelvinparmar** [comment]
Anyone is working on this issue?

**Comment by Pradumnasaraf** [comment]
Hey, @kelvinparmar no one is working on this. You have added steps to create a project board for a repo/project. Linke [this)(https://github.com/Pradumnasaraf/open-source-with-pradumna/projects/1)

**Comment by ampsteric** [comment]
hey! , I would be happy to help.
Please assign me this issue under hacktoberfest.

**Comment by Vishrut19** [comment]
Hey @Pradumnasaraf Can I work on this issue for Hacktoberfest ?

**Comment by Pradumnasaraf** [comment]
> Hey @Pradumnasaraf Can I work on this issue for Hacktoberfest ?

yes go ahead @Vishrut19

**Comment by ampsteric** [comment]
@Pradumnasaraf I asked to work on this issue before

**Comment by Pradumnasaraf** [comment]
Hey, @Vishrut19, by mistake I assigned the issue to you, sorry for the inconvenience. You can look for other issues.

@ampsteric assigning it to you.

**Comment by kelvinparmar** [comment]
Hi @Pradumnasaraf  sorry I am busy with my college life . you have assigned this issue to anyone?

**Comment by Pradumnasaraf** [comment]
> Hi @Pradumnasaraf sorry I am busy with my college life . you have assigned this issue to anyone?

You already made the PR, there we no response from your side. Okay, we will accept that. Hey @ampsteric sorry for inconvenience, please looks for some other issues
